/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.218.0Release
// Tag = production/release/21.218.0-0-g96fee6d7
/////////////////////////////////////////////////////////////////////////////////////////////


open class BatteryMesg : Mesg {
    public static let timestampFieldNum:UInt8 = 253
    public static let capacityFieldNum:UInt8 = 2

	public init() {
        super.init(mesg: BatteryMesg.createBatteryMesg())
    }

    public override init(mesg: Mesg) {
        super.init(mesg: mesg)
    }

    fileprivate override init(name: String, num: UInt16) {
        super.init(name: name, num: num)
    }

	public func getTimestamp() -> DateTime? {
		guard let value = getFieldValue(fieldNum: BatteryMesg.timestampFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setTimestamp(_ value: DateTime) throws {
		try setFieldValue(fieldNum: BatteryMesg.timestampFieldNum, value: value.timestamp)
	}

	public func getCapacity() -> UInt8? {
		guard let value = getFieldValue(fieldNum: BatteryMesg.capacityFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value
	}

	public func setCapacity(_ value: UInt8) throws {
		try setFieldValue(fieldNum: BatteryMesg.capacityFieldNum, value: value)
	}

	public class func createBatteryMesg() -> BatteryMesg {
        let mesg = BatteryMesg(name: "Battery", num: Profile.MesgNum.battery)
		
		mesg.fields[BatteryMesg.timestampFieldNum] = Field(name: "Timestamp", num: BatteryMesg.timestampFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[BatteryMesg.capacityFieldNum] = Field(name: "Capacity", num: BatteryMesg.capacityFieldNum, type: BaseType.UINT8.rawValue, scale: 1, offset: 0, units: "%", accumulated: false)
        return mesg
    }
}