/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.192.0Release
// Tag = production/release/21.192.0-0-g07f2955
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

public protocol FileCreatorMesgListener: AnyObject {
    func onMesg(_ mesg: FileCreatorMesg) throws
}

