/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.202.0Release
// Tag = production/release/21.202.0-0-g9a57aebc
/////////////////////////////////////////////////////////////////////////////////////////////


open class NapEventMesg : Mesg {
    public static let messageIndexFieldNum:UInt8 = 254
    public static let timestampFieldNum:UInt8 = 253
    public static let startTimeFieldNum:UInt8 = 0
    public static let startTimezoneOffsetFieldNum:UInt8 = 1
    public static let endTimeFieldNum:UInt8 = 2
    public static let endTimezoneOffsetFieldNum:UInt8 = 3
    public static let feedbackFieldNum:UInt8 = 4
    public static let isDeletedFieldNum:UInt8 = 5
    public static let sourceFieldNum:UInt8 = 6
    public static let updateTimestampFieldNum:UInt8 = 7

	public init() {
        super.init(mesg: NapEventMesg.createNapEventMesg())
    }

    public override init(mesg: Mesg) {
        super.init(mesg: mesg)
    }

    fileprivate override init(name: String, num: UInt16) {
        super.init(name: name, num: num)
    }

	public func getMessageIndex() -> MessageIndex? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.messageIndexFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMessageIndex(_ value: MessageIndex) throws {
		try setFieldValue(fieldNum: NapEventMesg.messageIndexFieldNum, value: value)
	}

	public func getTimestamp() -> DateTime? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.timestampFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setTimestamp(_ value: DateTime) throws {
		try setFieldValue(fieldNum: NapEventMesg.timestampFieldNum, value: value.timestamp)
	}

	public func getStartTime() -> DateTime? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.startTimeFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setStartTime(_ value: DateTime) throws {
		try setFieldValue(fieldNum: NapEventMesg.startTimeFieldNum, value: value.timestamp)
	}

	public func getStartTimezoneOffset() -> Int16? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.startTimezoneOffsetFieldNum, index:0) as? Int16 else {
            return nil
        }
		return value
	}

	public func setStartTimezoneOffset(_ value: Int16) throws {
		try setFieldValue(fieldNum: NapEventMesg.startTimezoneOffsetFieldNum, value: value)
	}

	public func getEndTime() -> DateTime? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.endTimeFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setEndTime(_ value: DateTime) throws {
		try setFieldValue(fieldNum: NapEventMesg.endTimeFieldNum, value: value.timestamp)
	}

	public func getEndTimezoneOffset() -> Int16? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.endTimezoneOffsetFieldNum, index:0) as? Int16 else {
            return nil
        }
		return value
	}

	public func setEndTimezoneOffset(_ value: Int16) throws {
		try setFieldValue(fieldNum: NapEventMesg.endTimezoneOffsetFieldNum, value: value)
	}

	public func getFeedback() -> NapPeriodFeedback? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.feedbackFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return NapPeriodFeedback(rawValue: value) ?? .invalid
	}

	public func setFeedback(_ value: NapPeriodFeedback) throws {
		try setFieldValue(fieldNum: NapEventMesg.feedbackFieldNum, value: value.rawValue)
	}

	public func getIsDeleted() -> Bool? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.isDeletedFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value == 1 ? true : false
	}

	public func setIsDeleted(_ value: Bool) throws {
		try setFieldValue(fieldNum: NapEventMesg.isDeletedFieldNum, value: value)
	}

	public func getSource() -> NapSource? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.sourceFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return NapSource(rawValue: value) ?? .invalid
	}

	public func setSource(_ value: NapSource) throws {
		try setFieldValue(fieldNum: NapEventMesg.sourceFieldNum, value: value.rawValue)
	}

	public func getUpdateTimestamp() -> DateTime? {
		guard let value = getFieldValue(fieldNum: NapEventMesg.updateTimestampFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setUpdateTimestamp(_ value: DateTime) throws {
		try setFieldValue(fieldNum: NapEventMesg.updateTimestampFieldNum, value: value.timestamp)
	}

	public class func createNapEventMesg() -> NapEventMesg {
        let mesg = NapEventMesg(name: "NapEvent", num: Profile.MesgNum.napEvent)
		
		mesg.fields[NapEventMesg.messageIndexFieldNum] = Field(name: "MessageIndex", num: NapEventMesg.messageIndexFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[NapEventMesg.timestampFieldNum] = Field(name: "Timestamp", num: NapEventMesg.timestampFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[NapEventMesg.startTimeFieldNum] = Field(name: "StartTime", num: NapEventMesg.startTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "seconds", accumulated: false)
		mesg.fields[NapEventMesg.startTimezoneOffsetFieldNum] = Field(name: "StartTimezoneOffset", num: NapEventMesg.startTimezoneOffsetFieldNum, type: BaseType.SINT16.rawValue, scale: 1, offset: 0, units: "minutes", accumulated: false)
		mesg.fields[NapEventMesg.endTimeFieldNum] = Field(name: "EndTime", num: NapEventMesg.endTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "seconds", accumulated: false)
		mesg.fields[NapEventMesg.endTimezoneOffsetFieldNum] = Field(name: "EndTimezoneOffset", num: NapEventMesg.endTimezoneOffsetFieldNum, type: BaseType.SINT16.rawValue, scale: 1, offset: 0, units: "minutes", accumulated: false)
		mesg.fields[NapEventMesg.feedbackFieldNum] = Field(name: "Feedback", num: NapEventMesg.feedbackFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[NapEventMesg.isDeletedFieldNum] = Field(name: "IsDeleted", num: NapEventMesg.isDeletedFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[NapEventMesg.sourceFieldNum] = Field(name: "Source", num: NapEventMesg.sourceFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[NapEventMesg.updateTimestampFieldNum] = Field(name: "UpdateTimestamp", num: NapEventMesg.updateTimestampFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
        return mesg
    }
}