/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.193.0Release
// Tag = production/release/21.193.0-0-g249913a
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

public protocol SleepDisruptionOvernightSeverityMesgListener: AnyObject {
    func onMesg(_ mesg: SleepDisruptionOvernightSeverityMesg) throws
}

