/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.218.0Release
// Tag = production/release/21.218.0-0-g96fee6d7
/////////////////////////////////////////////////////////////////////////////////////////////


open class SplitMesg : Mesg {
    public static let messageIndexFieldNum:UInt8 = 254
    public static let timestampFieldNum:UInt8 = 253
    public static let splitTypeFieldNum:UInt8 = 0
    public static let totalElapsedTimeFieldNum:UInt8 = 1
    public static let totalTimerTimeFieldNum:UInt8 = 2
    public static let totalDistanceFieldNum:UInt8 = 3
    public static let avgSpeedFieldNum:UInt8 = 4
    public static let startTimeFieldNum:UInt8 = 9
    public static let sportFieldNum:UInt8 = 11
    public static let subSportFieldNum:UInt8 = 12
    public static let totalAscentFieldNum:UInt8 = 13
    public static let totalDescentFieldNum:UInt8 = 14
    public static let avgHeartRateFieldNum:UInt8 = 15
    public static let maxHeartRateFieldNum:UInt8 = 16
    public static let necLatFieldNum:UInt8 = 17
    public static let necLongFieldNum:UInt8 = 18
    public static let swcLatFieldNum:UInt8 = 19
    public static let swcLongFieldNum:UInt8 = 20
    public static let startPositionLatFieldNum:UInt8 = 21
    public static let startPositionLongFieldNum:UInt8 = 22
    public static let endPositionLatFieldNum:UInt8 = 23
    public static let endPositionLongFieldNum:UInt8 = 24
    public static let maxSpeedFieldNum:UInt8 = 25
    public static let avgVertSpeedFieldNum:UInt8 = 26
    public static let endTimeFieldNum:UInt8 = 27
    public static let totalCaloriesFieldNum:UInt8 = 28
    public static let avgCadenceFieldNum:UInt8 = 29
    public static let maxCadenceFieldNum:UInt8 = 30
    public static let totalCyclesFieldNum:UInt8 = 31
    public static let avgTemperatureFieldNum:UInt8 = 32
    public static let maxTemperatureFieldNum:UInt8 = 33
    public static let minTemperatureFieldNum:UInt8 = 34
    public static let avgVerticalOscillationFieldNum:UInt8 = 35
    public static let avgVerticalRatioFieldNum:UInt8 = 36
    public static let avgStanceTimeFieldNum:UInt8 = 37
    public static let avgStanceTimeBalanceFieldNum:UInt8 = 38
    public static let avgStepLengthFieldNum:UInt8 = 39
    public static let avgPowerFieldNum:UInt8 = 40
    public static let maxPowerFieldNum:UInt8 = 41
    public static let normalizedPowerFieldNum:UInt8 = 42
    public static let leftRightBalanceFieldNum:UInt8 = 43
    public static let timeStandingFieldNum:UInt8 = 44
    public static let avgLeftPcoFieldNum:UInt8 = 45
    public static let avgRightPcoFieldNum:UInt8 = 46
    public static let avgLeftPowerPhaseFieldNum:UInt8 = 47
    public static let avgLeftPowerPhasePeakFieldNum:UInt8 = 48
    public static let avgRightPowerPhaseFieldNum:UInt8 = 49
    public static let avgRightPowerPhasePeakFieldNum:UInt8 = 50
    public static let avgPowerPositionFieldNum:UInt8 = 51
    public static let maxPowerPositionFieldNum:UInt8 = 52
    public static let avgLeftTorqueEffectivenessFieldNum:UInt8 = 53
    public static let avgRightTorqueEffectivenessFieldNum:UInt8 = 54
    public static let avgLeftPedalSmoothnessFieldNum:UInt8 = 55
    public static let avgRightPedalSmoothnessFieldNum:UInt8 = 56
    public static let avgCombinedPedalSmoothnessFieldNum:UInt8 = 57
    public static let avgFlowFieldNum:UInt8 = 58
    public static let totalGritFieldNum:UInt8 = 59
    public static let swimStrokeFieldNum:UInt8 = 62
    public static let numActiveLengthsFieldNum:UInt8 = 63
    public static let avgSwolfFieldNum:UInt8 = 64
    public static let avgStrokeDistanceFieldNum:UInt8 = 65
    public static let avgStrokesPerLengthFieldNum:UInt8 = 66
    public static let firstLapIndexFieldNum:UInt8 = 67
    public static let numLapsFieldNum:UInt8 = 68
    public static let climbGradingScaleFieldNum:UInt8 = 69
    public static let climbGradeValueFieldNum:UInt8 = 70
    public static let statusFieldNum:UInt8 = 71
    public static let numFallsFieldNum:UInt8 = 72
    public static let climbSendFieldNum:UInt8 = 73
    public static let startElevationFieldNum:UInt8 = 74
    public static let activeTimeFieldNum:UInt8 = 78
    public static let metabolicCaloriesFieldNum:UInt8 = 79
    public static let totalFractionalAscentFieldNum:UInt8 = 80
    public static let totalFractionalDescentFieldNum:UInt8 = 81
    public static let avgGradeFieldNum:UInt8 = 88
    public static let maxGradeFieldNum:UInt8 = 89
    public static let minCadenceFieldNum:UInt8 = 90
    public static let avgGradeAdjustedSpeedFieldNum:UInt8 = 93
    public static let avgStressFieldNum:UInt8 = 94
    public static let avgVamFieldNum:UInt8 = 99
    public static let jumpCountFieldNum:UInt8 = 104
    public static let totalMovingTimeFieldNum:UInt8 = 110
    public static let diveSectionTypeFieldNum:UInt8 = 112
    public static let avgAscentRateFieldNum:UInt8 = 113
    public static let maxAscentRateFieldNum:UInt8 = 114
    public static let avgDescentRateFieldNum:UInt8 = 115
    public static let maxDescentRateFieldNum:UInt8 = 116
    public static let totalAscentTimeFieldNum:UInt8 = 117
    public static let totalDescentTimeFieldNum:UInt8 = 118
    public static let totalHangTimeFieldNum:UInt8 = 119
    public static let apneaDisciplineFieldNum:UInt8 = 120
    public static let avgDepthFieldNum:UInt8 = 121
    public static let maxDepthFieldNum:UInt8 = 122
    public static let minHeartRateFieldNum:UInt8 = 124
    public static let surfaceIntervalFieldNum:UInt8 = 127
    public static let totalFractionalCyclesFieldNum:UInt8 = 142
    public static let avgStanceTimePercentFieldNum:UInt8 = 144
    public static let totalAnaerobicTrainingEffectFieldNum:UInt8 = 168
    public static let frontGearShiftCountFieldNum:UInt8 = 169
    public static let rearGearShiftCountFieldNum:UInt8 = 170

	private struct AvgCadenceSubField {
        public static let avgRunningCadence:UInt16 = 0
        public static let avgSwimmingCadence:UInt16 = 1
        public static let avgPaddlesportCadence:UInt16 = 2
        public static let avgPushCadence:UInt16 = 3
        public static let subfields:UInt16 = 4
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	private struct MaxCadenceSubField {
        public static let maxRunningCadence:UInt16 = 0
        public static let maxSwimmingCadence:UInt16 = 1
        public static let maxPaddlesportCadence:UInt16 = 2
        public static let maxPushCadence:UInt16 = 3
        public static let subfields:UInt16 = 4
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	private struct TotalCyclesSubField {
        public static let totalStrides:UInt16 = 0
        public static let totalStrokes:UInt16 = 1
        public static let totalReps:UInt16 = 2
        public static let totalPushes:UInt16 = 3
        public static let subfields:UInt16 = 4
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	private struct ClimbGradeValueSubField {
        public static let climbGradeYds:UInt16 = 0
        public static let climbGradeUiaa:UInt16 = 1
        public static let climbGradeFrench:UInt16 = 2
        public static let climbGradeBritishAdjectival:UInt16 = 3
        public static let climbGradeBritishTechnical:UInt16 = 4
        public static let climbGradeEwbank:UInt16 = 5
        public static let climbGradeBrazilian:UInt16 = 6
        public static let climbGradeSaxon:UInt16 = 7
        public static let climbGradeVermin:UInt16 = 8
        public static let climbGradeFont:UInt16 = 9
        public static let climbGradeDankyu:UInt16 = 10
        public static let subfields:UInt16 = 11
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	private struct MinCadenceSubField {
        public static let minRunningCadence:UInt16 = 0
        public static let minSwimmingCadence:UInt16 = 1
        public static let minPaddlesportCadence:UInt16 = 2
        public static let minPushCadence:UInt16 = 3
        public static let subfields:UInt16 = 4
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	public init() {
        super.init(mesg: SplitMesg.createSplitMesg())
    }

    public override init(mesg: Mesg) {
        super.init(mesg: mesg)
    }

    fileprivate override init(name: String, num: UInt16) {
        super.init(name: name, num: num)
    }

	public func getMessageIndex() -> MessageIndex? {
		guard let value = getFieldValue(fieldNum: SplitMesg.messageIndexFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMessageIndex(_ value: MessageIndex) throws {
		try setFieldValue(fieldNum: SplitMesg.messageIndexFieldNum, value: value)
	}

	public func getTimestamp() -> DateTime? {
		guard let value = getFieldValue(fieldNum: SplitMesg.timestampFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setTimestamp(_ value: DateTime) throws {
		try setFieldValue(fieldNum: SplitMesg.timestampFieldNum, value: value.timestamp)
	}

	public func getSplitType() -> SplitType? {
		guard let value = getFieldValue(fieldNum: SplitMesg.splitTypeFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return SplitType(rawValue: value) ?? .invalid
	}

	public func setSplitType(_ value: SplitType) throws {
		try setFieldValue(fieldNum: SplitMesg.splitTypeFieldNum, value: value.rawValue)
	}

	public func getTotalElapsedTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalElapsedTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalElapsedTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalElapsedTimeFieldNum, value: value)
	}

	public func getTotalTimerTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalTimerTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalTimerTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalTimerTimeFieldNum, value: value)
	}

	public func getTotalDistance() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalDistanceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalDistance(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalDistanceFieldNum, value: value)
	}

	public func getAvgSpeed() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgSpeedFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgSpeed(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgSpeedFieldNum, value: value)
	}

	public func getStartTime() -> DateTime? {
		guard let value = getFieldValue(fieldNum: SplitMesg.startTimeFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setStartTime(_ value: DateTime) throws {
		try setFieldValue(fieldNum: SplitMesg.startTimeFieldNum, value: value.timestamp)
	}

	public func getSport() -> Sport? {
		guard let value = getFieldValue(fieldNum: SplitMesg.sportFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return Sport(rawValue: value) ?? .invalid
	}

	public func setSport(_ value: Sport) throws {
		try setFieldValue(fieldNum: SplitMesg.sportFieldNum, value: value.rawValue)
	}

	public func getSubSport() -> SubSport? {
		guard let value = getFieldValue(fieldNum: SplitMesg.subSportFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return SubSport(rawValue: value) ?? .invalid
	}

	public func setSubSport(_ value: SubSport) throws {
		try setFieldValue(fieldNum: SplitMesg.subSportFieldNum, value: value.rawValue)
	}

	public func getTotalAscent() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalAscentFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setTotalAscent(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.totalAscentFieldNum, value: value)
	}

	public func getTotalDescent() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalDescentFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setTotalDescent(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.totalDescentFieldNum, value: value)
	}

	public func getAvgHeartRate() -> UInt8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgHeartRateFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value
	}

	public func setAvgHeartRate(_ value: UInt8) throws {
		try setFieldValue(fieldNum: SplitMesg.avgHeartRateFieldNum, value: value)
	}

	public func getMaxHeartRate() -> UInt8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxHeartRateFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value
	}

	public func setMaxHeartRate(_ value: UInt8) throws {
		try setFieldValue(fieldNum: SplitMesg.maxHeartRateFieldNum, value: value)
	}

	public func getNecLat() -> Int32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.necLatFieldNum, index:0) as? Int32 else {
            return nil
        }
		return value
	}

	public func setNecLat(_ value: Int32) throws {
		try setFieldValue(fieldNum: SplitMesg.necLatFieldNum, value: value)
	}

	public func getNecLong() -> Int32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.necLongFieldNum, index:0) as? Int32 else {
            return nil
        }
		return value
	}

	public func setNecLong(_ value: Int32) throws {
		try setFieldValue(fieldNum: SplitMesg.necLongFieldNum, value: value)
	}

	public func getSwcLat() -> Int32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.swcLatFieldNum, index:0) as? Int32 else {
            return nil
        }
		return value
	}

	public func setSwcLat(_ value: Int32) throws {
		try setFieldValue(fieldNum: SplitMesg.swcLatFieldNum, value: value)
	}

	public func getSwcLong() -> Int32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.swcLongFieldNum, index:0) as? Int32 else {
            return nil
        }
		return value
	}

	public func setSwcLong(_ value: Int32) throws {
		try setFieldValue(fieldNum: SplitMesg.swcLongFieldNum, value: value)
	}

	public func getStartPositionLat() -> Int32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.startPositionLatFieldNum, index:0) as? Int32 else {
            return nil
        }
		return value
	}

	public func setStartPositionLat(_ value: Int32) throws {
		try setFieldValue(fieldNum: SplitMesg.startPositionLatFieldNum, value: value)
	}

	public func getStartPositionLong() -> Int32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.startPositionLongFieldNum, index:0) as? Int32 else {
            return nil
        }
		return value
	}

	public func setStartPositionLong(_ value: Int32) throws {
		try setFieldValue(fieldNum: SplitMesg.startPositionLongFieldNum, value: value)
	}

	public func getEndPositionLat() -> Int32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.endPositionLatFieldNum, index:0) as? Int32 else {
            return nil
        }
		return value
	}

	public func setEndPositionLat(_ value: Int32) throws {
		try setFieldValue(fieldNum: SplitMesg.endPositionLatFieldNum, value: value)
	}

	public func getEndPositionLong() -> Int32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.endPositionLongFieldNum, index:0) as? Int32 else {
            return nil
        }
		return value
	}

	public func setEndPositionLong(_ value: Int32) throws {
		try setFieldValue(fieldNum: SplitMesg.endPositionLongFieldNum, value: value)
	}

	public func getMaxSpeed() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxSpeedFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxSpeed(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxSpeedFieldNum, value: value)
	}

	public func getAvgVertSpeed() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgVertSpeedFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgVertSpeed(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgVertSpeedFieldNum, value: value)
	}

	public func getEndTime() -> DateTime? {
		guard let value = getFieldValue(fieldNum: SplitMesg.endTimeFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setEndTime(_ value: DateTime) throws {
		try setFieldValue(fieldNum: SplitMesg.endTimeFieldNum, value: value.timestamp)
	}

	public func getTotalCalories() -> UInt32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalCaloriesFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return value
	}

	public func setTotalCalories(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitMesg.totalCaloriesFieldNum, value: value)
	}

	public func getAvgCadence() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, value: value)
	}

	public func getAvgRunningCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, index: 0, subFieldIndex: AvgCadenceSubField.avgRunningCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setAvgRunningCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, value: value, index: 0, subFieldIndex: AvgCadenceSubField.avgRunningCadence )
	}

	public func getAvgSwimmingCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, index: 0, subFieldIndex: AvgCadenceSubField.avgSwimmingCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setAvgSwimmingCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, value: value, index: 0, subFieldIndex: AvgCadenceSubField.avgSwimmingCadence )
	}

	public func getAvgPaddlesportCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, index: 0, subFieldIndex: AvgCadenceSubField.avgPaddlesportCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setAvgPaddlesportCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, value: value, index: 0, subFieldIndex: AvgCadenceSubField.avgPaddlesportCadence )
	}

	public func getAvgPushCadence() throws -> UInt16? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, index: 0, subFieldIndex: AvgCadenceSubField.avgPushCadence).map({UInt16(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setAvgPushCadence(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.avgCadenceFieldNum, value: value, index: 0, subFieldIndex: AvgCadenceSubField.avgPushCadence )
	}

	public func getMaxCadence() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, value: value)
	}

	public func getMaxRunningCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, index: 0, subFieldIndex: MaxCadenceSubField.maxRunningCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMaxRunningCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, value: value, index: 0, subFieldIndex: MaxCadenceSubField.maxRunningCadence )
	}

	public func getMaxSwimmingCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, index: 0, subFieldIndex: MaxCadenceSubField.maxSwimmingCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMaxSwimmingCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, value: value, index: 0, subFieldIndex: MaxCadenceSubField.maxSwimmingCadence )
	}

	public func getMaxPaddlesportCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, index: 0, subFieldIndex: MaxCadenceSubField.maxPaddlesportCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMaxPaddlesportCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, value: value, index: 0, subFieldIndex: MaxCadenceSubField.maxPaddlesportCadence )
	}

	public func getMaxPushCadence() throws -> UInt16? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, index: 0, subFieldIndex: MaxCadenceSubField.maxPushCadence).map({UInt16(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMaxPushCadence(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.maxCadenceFieldNum, value: value, index: 0, subFieldIndex: MaxCadenceSubField.maxPushCadence )
	}

	public func getTotalCycles() -> UInt32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return value
	}

	public func setTotalCycles(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, value: value)
	}

	public func getTotalStrides() throws -> UInt32? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, index: 0, subFieldIndex: TotalCyclesSubField.totalStrides).map({UInt32(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setTotalStrides(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, value: value, index: 0, subFieldIndex: TotalCyclesSubField.totalStrides )
	}

	public func getTotalStrokes() throws -> UInt32? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, index: 0, subFieldIndex: TotalCyclesSubField.totalStrokes).map({UInt32(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setTotalStrokes(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, value: value, index: 0, subFieldIndex: TotalCyclesSubField.totalStrokes )
	}

	public func getTotalReps() throws -> UInt32? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, index: 0, subFieldIndex: TotalCyclesSubField.totalReps).map({UInt32(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setTotalReps(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, value: value, index: 0, subFieldIndex: TotalCyclesSubField.totalReps )
	}

	public func getTotalPushes() throws -> UInt32? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, index: 0, subFieldIndex: TotalCyclesSubField.totalPushes).map({UInt32(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setTotalPushes(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitMesg.totalCyclesFieldNum, value: value, index: 0, subFieldIndex: TotalCyclesSubField.totalPushes )
	}

	public func getAvgTemperature() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgTemperatureFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setAvgTemperature(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitMesg.avgTemperatureFieldNum, value: value)
	}

	public func getMaxTemperature() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxTemperatureFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setMaxTemperature(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitMesg.maxTemperatureFieldNum, value: value)
	}

	public func getMinTemperature() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.minTemperatureFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setMinTemperature(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitMesg.minTemperatureFieldNum, value: value)
	}

	public func getAvgVerticalOscillation() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgVerticalOscillationFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgVerticalOscillation(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgVerticalOscillationFieldNum, value: value)
	}

	public func getAvgVerticalRatio() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgVerticalRatioFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgVerticalRatio(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgVerticalRatioFieldNum, value: value)
	}

	public func getAvgStanceTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgStanceTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStanceTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgStanceTimeFieldNum, value: value)
	}

	public func getAvgStanceTimeBalance() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgStanceTimeBalanceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStanceTimeBalance(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgStanceTimeBalanceFieldNum, value: value)
	}

	public func getAvgStepLength() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgStepLengthFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStepLength(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgStepLengthFieldNum, value: value)
	}

	public func getAvgPower() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgPowerFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgPower(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.avgPowerFieldNum, value: value)
	}

	public func getMaxPower() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxPowerFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMaxPower(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.maxPowerFieldNum, value: value)
	}

	public func getNormalizedPower() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.normalizedPowerFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNormalizedPower(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.normalizedPowerFieldNum, value: value)
	}

	public func getLeftRightBalance() -> LeftRightBalance100? {
		guard let value = getFieldValue(fieldNum: SplitMesg.leftRightBalanceFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setLeftRightBalance(_ value: LeftRightBalance100) throws {
		try setFieldValue(fieldNum: SplitMesg.leftRightBalanceFieldNum, value: value)
	}

	public func getTimeStanding() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.timeStandingFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTimeStanding(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.timeStandingFieldNum, value: value)
	}

	public func getAvgLeftPco() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgLeftPcoFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setAvgLeftPco(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitMesg.avgLeftPcoFieldNum, value: value)
	}

	public func getAvgRightPco() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgRightPcoFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setAvgRightPco(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitMesg.avgRightPcoFieldNum, value: value)
	}

	public func getNumAvgLeftPowerPhase() -> UInt8 {
		guard let field = getField(fieldNum: SplitMesg.avgLeftPowerPhaseFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgLeftPowerPhase() -> [Float64?]? {
		guard let field = getField(fieldNum: SplitMesg.avgLeftPowerPhaseFieldNum) else {
			return nil
		}
		return field.toArray() as [Float64?]
	}

	public func getAvgLeftPowerPhase(index: Int) -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgLeftPowerPhaseFieldNum, index: index) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgLeftPowerPhase(index: Int, value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgLeftPowerPhaseFieldNum, value: value, index: index)
	}

	public func getNumAvgLeftPowerPhasePeak() -> UInt8 {
		guard let field = getField(fieldNum: SplitMesg.avgLeftPowerPhasePeakFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgLeftPowerPhasePeak() -> [Float64?]? {
		guard let field = getField(fieldNum: SplitMesg.avgLeftPowerPhasePeakFieldNum) else {
			return nil
		}
		return field.toArray() as [Float64?]
	}

	public func getAvgLeftPowerPhasePeak(index: Int) -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgLeftPowerPhasePeakFieldNum, index: index) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgLeftPowerPhasePeak(index: Int, value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgLeftPowerPhasePeakFieldNum, value: value, index: index)
	}

	public func getNumAvgRightPowerPhase() -> UInt8 {
		guard let field = getField(fieldNum: SplitMesg.avgRightPowerPhaseFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgRightPowerPhase() -> [Float64?]? {
		guard let field = getField(fieldNum: SplitMesg.avgRightPowerPhaseFieldNum) else {
			return nil
		}
		return field.toArray() as [Float64?]
	}

	public func getAvgRightPowerPhase(index: Int) -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgRightPowerPhaseFieldNum, index: index) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgRightPowerPhase(index: Int, value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgRightPowerPhaseFieldNum, value: value, index: index)
	}

	public func getNumAvgRightPowerPhasePeak() -> UInt8 {
		guard let field = getField(fieldNum: SplitMesg.avgRightPowerPhasePeakFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgRightPowerPhasePeak() -> [Float64?]? {
		guard let field = getField(fieldNum: SplitMesg.avgRightPowerPhasePeakFieldNum) else {
			return nil
		}
		return field.toArray() as [Float64?]
	}

	public func getAvgRightPowerPhasePeak(index: Int) -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgRightPowerPhasePeakFieldNum, index: index) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgRightPowerPhasePeak(index: Int, value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgRightPowerPhasePeakFieldNum, value: value, index: index)
	}

	public func getNumAvgPowerPosition() -> UInt8 {
		guard let field = getField(fieldNum: SplitMesg.avgPowerPositionFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgPowerPosition() -> [UInt16?]? {
		guard let field = getField(fieldNum: SplitMesg.avgPowerPositionFieldNum) else {
			return nil
		}
		return field.toArray() as [UInt16?]
	}

	public func getAvgPowerPosition(index: Int) -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgPowerPositionFieldNum, index: index) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgPowerPosition(index: Int, value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.avgPowerPositionFieldNum, value: value, index: index)
	}

	public func getNumMaxPowerPosition() -> UInt8 {
		guard let field = getField(fieldNum: SplitMesg.maxPowerPositionFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getMaxPowerPosition() -> [UInt16?]? {
		guard let field = getField(fieldNum: SplitMesg.maxPowerPositionFieldNum) else {
			return nil
		}
		return field.toArray() as [UInt16?]
	}

	public func getMaxPowerPosition(index: Int) -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxPowerPositionFieldNum, index: index) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMaxPowerPosition(index: Int, value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.maxPowerPositionFieldNum, value: value, index: index)
	}

	public func getAvgLeftTorqueEffectiveness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgLeftTorqueEffectivenessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgLeftTorqueEffectiveness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgLeftTorqueEffectivenessFieldNum, value: value)
	}

	public func getAvgRightTorqueEffectiveness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgRightTorqueEffectivenessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgRightTorqueEffectiveness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgRightTorqueEffectivenessFieldNum, value: value)
	}

	public func getAvgLeftPedalSmoothness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgLeftPedalSmoothnessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgLeftPedalSmoothness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgLeftPedalSmoothnessFieldNum, value: value)
	}

	public func getAvgRightPedalSmoothness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgRightPedalSmoothnessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgRightPedalSmoothness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgRightPedalSmoothnessFieldNum, value: value)
	}

	public func getAvgCombinedPedalSmoothness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgCombinedPedalSmoothnessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgCombinedPedalSmoothness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgCombinedPedalSmoothnessFieldNum, value: value)
	}

	public func getAvgFlow() -> Float32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgFlowFieldNum, index:0) as? Float32 else {
            return nil
        }
		return value
	}

	public func setAvgFlow(_ value: Float32) throws {
		try setFieldValue(fieldNum: SplitMesg.avgFlowFieldNum, value: value)
	}

	public func getTotalGrit() -> Float32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalGritFieldNum, index:0) as? Float32 else {
            return nil
        }
		return value
	}

	public func setTotalGrit(_ value: Float32) throws {
		try setFieldValue(fieldNum: SplitMesg.totalGritFieldNum, value: value)
	}

	public func getSwimStroke() -> SwimStroke? {
		guard let value = getFieldValue(fieldNum: SplitMesg.swimStrokeFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return SwimStroke(rawValue: value) ?? .invalid
	}

	public func setSwimStroke(_ value: SwimStroke) throws {
		try setFieldValue(fieldNum: SplitMesg.swimStrokeFieldNum, value: value.rawValue)
	}

	public func getNumActiveLengths() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.numActiveLengthsFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNumActiveLengths(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.numActiveLengthsFieldNum, value: value)
	}

	public func getAvgSwolf() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgSwolfFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgSwolf(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.avgSwolfFieldNum, value: value)
	}

	public func getAvgStrokeDistance() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgStrokeDistanceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStrokeDistance(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgStrokeDistanceFieldNum, value: value)
	}

	public func getAvgStrokesPerLength() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgStrokesPerLengthFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStrokesPerLength(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgStrokesPerLengthFieldNum, value: value)
	}

	public func getFirstLapIndex() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.firstLapIndexFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setFirstLapIndex(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.firstLapIndexFieldNum, value: value)
	}

	public func getNumLaps() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.numLapsFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNumLaps(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.numLapsFieldNum, value: value)
	}

	public func getClimbGradingScale() -> ClimbGradingScale? {
		guard let value = getFieldValue(fieldNum: SplitMesg.climbGradingScaleFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return ClimbGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradingScale(_ value: ClimbGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradingScaleFieldNum, value: value.rawValue)
	}

	public func getClimbGradeValue() -> UInt32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return value
	}

	public func setClimbGradeValue(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value)
	}

	public func getClimbGradeYds() throws -> YdsGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeYds).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return YdsGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeYds(_ value: YdsGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeYds )
	}

	public func getClimbGradeUiaa() throws -> UiaaGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeUiaa).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return UiaaGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeUiaa(_ value: UiaaGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeUiaa )
	}

	public func getClimbGradeFrench() throws -> FrenchGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeFrench).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return FrenchGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeFrench(_ value: FrenchGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeFrench )
	}

	public func getClimbGradeBritishAdjectival() throws -> BritishAdjectivalGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeBritishAdjectival).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return BritishAdjectivalGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeBritishAdjectival(_ value: BritishAdjectivalGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeBritishAdjectival )
	}

	public func getClimbGradeBritishTechnical() throws -> BritishTechnicalGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeBritishTechnical).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return BritishTechnicalGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeBritishTechnical(_ value: BritishTechnicalGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeBritishTechnical )
	}

	public func getClimbGradeEwbank() throws -> EwbankGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeEwbank).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return EwbankGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeEwbank(_ value: EwbankGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeEwbank )
	}

	public func getClimbGradeBrazilian() throws -> BrazilianGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeBrazilian).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return BrazilianGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeBrazilian(_ value: BrazilianGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeBrazilian )
	}

	public func getClimbGradeSaxon() throws -> SaxonGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeSaxon).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return SaxonGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeSaxon(_ value: SaxonGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeSaxon )
	}

	public func getClimbGradeVermin() throws -> VerminGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeVermin).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return VerminGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeVermin(_ value: VerminGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeVermin )
	}

	public func getClimbGradeFont() throws -> FontGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeFont).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return FontGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeFont(_ value: FontGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeFont )
	}

	public func getClimbGradeDankyu() throws -> DankyuGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeDankyu).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return DankyuGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradeDankyu(_ value: DankyuGradingScale) throws {
		try setFieldValue(fieldNum: SplitMesg.climbGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbGradeValueSubField.climbGradeDankyu )
	}

	public func getStatus() -> SplitStatus? {
		guard let value = getFieldValue(fieldNum: SplitMesg.statusFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return SplitStatus(rawValue: value) ?? .invalid
	}

	public func setStatus(_ value: SplitStatus) throws {
		try setFieldValue(fieldNum: SplitMesg.statusFieldNum, value: value.rawValue)
	}

	public func getNumFalls() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.numFallsFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNumFalls(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.numFallsFieldNum, value: value)
	}

	public func getClimbSend() -> Bool? {
		guard let value = getFieldValue(fieldNum: SplitMesg.climbSendFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value == 1 ? true : false
	}

	public func setClimbSend(_ value: Bool) throws {
		try setFieldValue(fieldNum: SplitMesg.climbSendFieldNum, value: value)
	}

	public func getStartElevation() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.startElevationFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setStartElevation(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.startElevationFieldNum, value: value)
	}

	public func getActiveTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.activeTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setActiveTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.activeTimeFieldNum, value: value)
	}

	public func getMetabolicCalories() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.metabolicCaloriesFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMetabolicCalories(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.metabolicCaloriesFieldNum, value: value)
	}

	public func getTotalFractionalAscent() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalFractionalAscentFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalFractionalAscent(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalFractionalAscentFieldNum, value: value)
	}

	public func getTotalFractionalDescent() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalFractionalDescentFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalFractionalDescent(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalFractionalDescentFieldNum, value: value)
	}

	public func getAvgGrade() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgGradeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgGrade(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgGradeFieldNum, value: value)
	}

	public func getMaxGrade() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxGradeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxGrade(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxGradeFieldNum, value: value)
	}

	public func getMinCadence() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMinCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, value: value)
	}

	public func getMinRunningCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, index: 0, subFieldIndex: MinCadenceSubField.minRunningCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMinRunningCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, value: value, index: 0, subFieldIndex: MinCadenceSubField.minRunningCadence )
	}

	public func getMinSwimmingCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, index: 0, subFieldIndex: MinCadenceSubField.minSwimmingCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMinSwimmingCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, value: value, index: 0, subFieldIndex: MinCadenceSubField.minSwimmingCadence )
	}

	public func getMinPaddlesportCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, index: 0, subFieldIndex: MinCadenceSubField.minPaddlesportCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMinPaddlesportCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, value: value, index: 0, subFieldIndex: MinCadenceSubField.minPaddlesportCadence )
	}

	public func getMinPushCadence() throws -> UInt16? {
		guard let value = try getFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, index: 0, subFieldIndex: MinCadenceSubField.minPushCadence).map({UInt16(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMinPushCadence(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.minCadenceFieldNum, value: value, index: 0, subFieldIndex: MinCadenceSubField.minPushCadence )
	}

	public func getAvgGradeAdjustedSpeed() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgGradeAdjustedSpeedFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgGradeAdjustedSpeed(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgGradeAdjustedSpeedFieldNum, value: value)
	}

	public func getAvgStress() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgStressFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgStress(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.avgStressFieldNum, value: value)
	}

	public func getAvgVam() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgVamFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgVam(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgVamFieldNum, value: value)
	}

	public func getJumpCount() -> UInt8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.jumpCountFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value
	}

	public func setJumpCount(_ value: UInt8) throws {
		try setFieldValue(fieldNum: SplitMesg.jumpCountFieldNum, value: value)
	}

	public func getTotalMovingTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalMovingTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalMovingTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalMovingTimeFieldNum, value: value)
	}

	public func getDiveSectionType() -> DiveSectionType? {
		guard let value = getFieldValue(fieldNum: SplitMesg.diveSectionTypeFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return DiveSectionType(rawValue: value) ?? .invalid
	}

	public func setDiveSectionType(_ value: DiveSectionType) throws {
		try setFieldValue(fieldNum: SplitMesg.diveSectionTypeFieldNum, value: value.rawValue)
	}

	public func getAvgAscentRate() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgAscentRateFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgAscentRate(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgAscentRateFieldNum, value: value)
	}

	public func getMaxAscentRate() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxAscentRateFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxAscentRate(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxAscentRateFieldNum, value: value)
	}

	public func getAvgDescentRate() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgDescentRateFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgDescentRate(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgDescentRateFieldNum, value: value)
	}

	public func getMaxDescentRate() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxDescentRateFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxDescentRate(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxDescentRateFieldNum, value: value)
	}

	public func getTotalAscentTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalAscentTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalAscentTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalAscentTimeFieldNum, value: value)
	}

	public func getTotalDescentTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalDescentTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalDescentTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalDescentTimeFieldNum, value: value)
	}

	public func getTotalHangTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalHangTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalHangTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalHangTimeFieldNum, value: value)
	}

	public func getApneaDiscipline() -> ApneaDiscipline? {
		guard let value = getFieldValue(fieldNum: SplitMesg.apneaDisciplineFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return ApneaDiscipline(rawValue: value) ?? .invalid
	}

	public func setApneaDiscipline(_ value: ApneaDiscipline) throws {
		try setFieldValue(fieldNum: SplitMesg.apneaDisciplineFieldNum, value: value.rawValue)
	}

	public func getAvgDepth() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgDepthFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgDepth(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgDepthFieldNum, value: value)
	}

	public func getMaxDepth() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.maxDepthFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxDepth(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.maxDepthFieldNum, value: value)
	}

	public func getMinHeartRate() -> UInt8? {
		guard let value = getFieldValue(fieldNum: SplitMesg.minHeartRateFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value
	}

	public func setMinHeartRate(_ value: UInt8) throws {
		try setFieldValue(fieldNum: SplitMesg.minHeartRateFieldNum, value: value)
	}

	public func getSurfaceInterval() -> UInt32? {
		guard let value = getFieldValue(fieldNum: SplitMesg.surfaceIntervalFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return value
	}

	public func setSurfaceInterval(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitMesg.surfaceIntervalFieldNum, value: value)
	}

	public func getTotalFractionalCycles() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalFractionalCyclesFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalFractionalCycles(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalFractionalCyclesFieldNum, value: value)
	}

	public func getAvgStanceTimePercent() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.avgStanceTimePercentFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStanceTimePercent(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.avgStanceTimePercentFieldNum, value: value)
	}

	public func getTotalAnaerobicTrainingEffect() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitMesg.totalAnaerobicTrainingEffectFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalAnaerobicTrainingEffect(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitMesg.totalAnaerobicTrainingEffectFieldNum, value: value)
	}

	public func getFrontGearShiftCount() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.frontGearShiftCountFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setFrontGearShiftCount(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.frontGearShiftCountFieldNum, value: value)
	}

	public func getRearGearShiftCount() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitMesg.rearGearShiftCountFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setRearGearShiftCount(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitMesg.rearGearShiftCountFieldNum, value: value)
	}

	public class func createSplitMesg() -> SplitMesg {
        let mesg = SplitMesg(name: "Split", num: Profile.MesgNum.split)
		
		mesg.fields[SplitMesg.messageIndexFieldNum] = Field(name: "MessageIndex", num: SplitMesg.messageIndexFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.timestampFieldNum] = Field(name: "Timestamp", num: SplitMesg.timestampFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.splitTypeFieldNum] = Field(name: "SplitType", num: SplitMesg.splitTypeFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.totalElapsedTimeFieldNum] = Field(name: "TotalElapsedTime", num: SplitMesg.totalElapsedTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.totalTimerTimeFieldNum] = Field(name: "TotalTimerTime", num: SplitMesg.totalTimerTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.totalDistanceFieldNum] = Field(name: "TotalDistance", num: SplitMesg.totalDistanceFieldNum, type: BaseType.UINT32.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitMesg.avgSpeedFieldNum] = Field(name: "AvgSpeed", num: SplitMesg.avgSpeedFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.startTimeFieldNum] = Field(name: "StartTime", num: SplitMesg.startTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.sportFieldNum] = Field(name: "Sport", num: SplitMesg.sportFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.subSportFieldNum] = Field(name: "SubSport", num: SplitMesg.subSportFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.totalAscentFieldNum] = Field(name: "TotalAscent", num: SplitMesg.totalAscentFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitMesg.totalDescentFieldNum] = Field(name: "TotalDescent", num: SplitMesg.totalDescentFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitMesg.avgHeartRateFieldNum] = Field(name: "AvgHeartRate", num: SplitMesg.avgHeartRateFieldNum, type: BaseType.UINT8.rawValue, scale: 1, offset: 0, units: "bpm", accumulated: false)
		mesg.fields[SplitMesg.maxHeartRateFieldNum] = Field(name: "MaxHeartRate", num: SplitMesg.maxHeartRateFieldNum, type: BaseType.UINT8.rawValue, scale: 1, offset: 0, units: "bpm", accumulated: false)
		mesg.fields[SplitMesg.necLatFieldNum] = Field(name: "NecLat", num: SplitMesg.necLatFieldNum, type: BaseType.SINT32.rawValue, scale: 1, offset: 0, units: "semicircles", accumulated: false)
		mesg.fields[SplitMesg.necLongFieldNum] = Field(name: "NecLong", num: SplitMesg.necLongFieldNum, type: BaseType.SINT32.rawValue, scale: 1, offset: 0, units: "semicircles", accumulated: false)
		mesg.fields[SplitMesg.swcLatFieldNum] = Field(name: "SwcLat", num: SplitMesg.swcLatFieldNum, type: BaseType.SINT32.rawValue, scale: 1, offset: 0, units: "semicircles", accumulated: false)
		mesg.fields[SplitMesg.swcLongFieldNum] = Field(name: "SwcLong", num: SplitMesg.swcLongFieldNum, type: BaseType.SINT32.rawValue, scale: 1, offset: 0, units: "semicircles", accumulated: false)
		mesg.fields[SplitMesg.startPositionLatFieldNum] = Field(name: "StartPositionLat", num: SplitMesg.startPositionLatFieldNum, type: BaseType.SINT32.rawValue, scale: 1, offset: 0, units: "semicircles", accumulated: false)
		mesg.fields[SplitMesg.startPositionLongFieldNum] = Field(name: "StartPositionLong", num: SplitMesg.startPositionLongFieldNum, type: BaseType.SINT32.rawValue, scale: 1, offset: 0, units: "semicircles", accumulated: false)
		mesg.fields[SplitMesg.endPositionLatFieldNum] = Field(name: "EndPositionLat", num: SplitMesg.endPositionLatFieldNum, type: BaseType.SINT32.rawValue, scale: 1, offset: 0, units: "semicircles", accumulated: false)
		mesg.fields[SplitMesg.endPositionLongFieldNum] = Field(name: "EndPositionLong", num: SplitMesg.endPositionLongFieldNum, type: BaseType.SINT32.rawValue, scale: 1, offset: 0, units: "semicircles", accumulated: false)
		mesg.fields[SplitMesg.maxSpeedFieldNum] = Field(name: "MaxSpeed", num: SplitMesg.maxSpeedFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.avgVertSpeedFieldNum] = Field(name: "AvgVertSpeed", num: SplitMesg.avgVertSpeedFieldNum, type: BaseType.SINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.endTimeFieldNum] = Field(name: "EndTime", num: SplitMesg.endTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.totalCaloriesFieldNum] = Field(name: "TotalCalories", num: SplitMesg.totalCaloriesFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "kcal", accumulated: false)
		mesg.fields[SplitMesg.avgCadenceFieldNum] = Field(name: "AvgCadence", num: SplitMesg.avgCadenceFieldNum, type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "rpm", accumulated: false)
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields.append(SubField(name: "AvgRunningCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strides/min"))
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgRunningCadence)].addMap(refFieldNum: 11, refFieldValue: 1)
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields.append(SubField(name: "AvgSwimmingCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgSwimmingCadence)].addMap(refFieldNum: 11, refFieldValue: 5)
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields.append(SubField(name: "AvgPaddlesportCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgPaddlesportCadence)].addMap(refFieldNum: 11, refFieldValue: 15)
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgPaddlesportCadence)].addMap(refFieldNum: 11, refFieldValue: 37)
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields.append(SubField(name: "AvgPushCadence", type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "pushes/min"))
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgPushCadence)].addMap(refFieldNum: 11, refFieldValue: 66)
        mesg.fields[SplitMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgPushCadence)].addMap(refFieldNum: 11, refFieldValue: 65)
		mesg.fields[SplitMesg.maxCadenceFieldNum] = Field(name: "MaxCadence", num: SplitMesg.maxCadenceFieldNum, type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "rpm", accumulated: false)
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields.append(SubField(name: "MaxRunningCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strides/min"))
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxRunningCadence)].addMap(refFieldNum: 11, refFieldValue: 1)
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields.append(SubField(name: "MaxSwimmingCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxSwimmingCadence)].addMap(refFieldNum: 11, refFieldValue: 5)
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields.append(SubField(name: "MaxPaddlesportCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxPaddlesportCadence)].addMap(refFieldNum: 11, refFieldValue: 15)
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxPaddlesportCadence)].addMap(refFieldNum: 11, refFieldValue: 37)
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields.append(SubField(name: "MaxPushCadence", type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "pushes/min"))
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxPushCadence)].addMap(refFieldNum: 11, refFieldValue: 66)
        mesg.fields[SplitMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxPushCadence)].addMap(refFieldNum: 11, refFieldValue: 65)
		mesg.fields[SplitMesg.totalCyclesFieldNum] = Field(name: "TotalCycles", num: SplitMesg.totalCyclesFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "cycles", accumulated: false)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields.append(SubField(name: "TotalStrides", type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "strides"))
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrides)].addMap(refFieldNum: 11, refFieldValue: 1)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrides)].addMap(refFieldNum: 11, refFieldValue: 11)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields.append(SubField(name: "TotalStrokes", type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "strokes"))
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrokes)].addMap(refFieldNum: 11, refFieldValue: 2)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrokes)].addMap(refFieldNum: 11, refFieldValue: 5)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrokes)].addMap(refFieldNum: 11, refFieldValue: 15)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrokes)].addMap(refFieldNum: 11, refFieldValue: 37)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields.append(SubField(name: "TotalReps", type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "reps"))
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalReps)].addMap(refFieldNum: 11, refFieldValue: 62)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields.append(SubField(name: "TotalPushes", type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "pushes"))
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalPushes)].addMap(refFieldNum: 11, refFieldValue: 66)
        mesg.fields[SplitMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalPushes)].addMap(refFieldNum: 11, refFieldValue: 65)
		mesg.fields[SplitMesg.avgTemperatureFieldNum] = Field(name: "AvgTemperature", num: SplitMesg.avgTemperatureFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "C", accumulated: false)
		mesg.fields[SplitMesg.maxTemperatureFieldNum] = Field(name: "MaxTemperature", num: SplitMesg.maxTemperatureFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "C", accumulated: false)
		mesg.fields[SplitMesg.minTemperatureFieldNum] = Field(name: "MinTemperature", num: SplitMesg.minTemperatureFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "C", accumulated: false)
		mesg.fields[SplitMesg.avgVerticalOscillationFieldNum] = Field(name: "AvgVerticalOscillation", num: SplitMesg.avgVerticalOscillationFieldNum, type: BaseType.UINT16.rawValue, scale: 10, offset: 0, units: "mm", accumulated: false)
		mesg.fields[SplitMesg.avgVerticalRatioFieldNum] = Field(name: "AvgVerticalRatio", num: SplitMesg.avgVerticalRatioFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitMesg.avgStanceTimeFieldNum] = Field(name: "AvgStanceTime", num: SplitMesg.avgStanceTimeFieldNum, type: BaseType.UINT16.rawValue, scale: 10, offset: 0, units: "ms", accumulated: false)
		mesg.fields[SplitMesg.avgStanceTimeBalanceFieldNum] = Field(name: "AvgStanceTimeBalance", num: SplitMesg.avgStanceTimeBalanceFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitMesg.avgStepLengthFieldNum] = Field(name: "AvgStepLength", num: SplitMesg.avgStepLengthFieldNum, type: BaseType.UINT16.rawValue, scale: 10, offset: 0, units: "mm", accumulated: false)
		mesg.fields[SplitMesg.avgPowerFieldNum] = Field(name: "AvgPower", num: SplitMesg.avgPowerFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitMesg.maxPowerFieldNum] = Field(name: "MaxPower", num: SplitMesg.maxPowerFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitMesg.normalizedPowerFieldNum] = Field(name: "NormalizedPower", num: SplitMesg.normalizedPowerFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitMesg.leftRightBalanceFieldNum] = Field(name: "LeftRightBalance", num: SplitMesg.leftRightBalanceFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.timeStandingFieldNum] = Field(name: "TimeStanding", num: SplitMesg.timeStandingFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.avgLeftPcoFieldNum] = Field(name: "AvgLeftPco", num: SplitMesg.avgLeftPcoFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "mm", accumulated: false)
		mesg.fields[SplitMesg.avgRightPcoFieldNum] = Field(name: "AvgRightPco", num: SplitMesg.avgRightPcoFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "mm", accumulated: false)
		mesg.fields[SplitMesg.avgLeftPowerPhaseFieldNum] = Field(name: "AvgLeftPowerPhase", num: SplitMesg.avgLeftPowerPhaseFieldNum, type: BaseType.UINT8.rawValue, scale: 0.7111111, offset: 0, units: "degrees", accumulated: false)
		mesg.fields[SplitMesg.avgLeftPowerPhasePeakFieldNum] = Field(name: "AvgLeftPowerPhasePeak", num: SplitMesg.avgLeftPowerPhasePeakFieldNum, type: BaseType.UINT8.rawValue, scale: 0.7111111, offset: 0, units: "degrees", accumulated: false)
		mesg.fields[SplitMesg.avgRightPowerPhaseFieldNum] = Field(name: "AvgRightPowerPhase", num: SplitMesg.avgRightPowerPhaseFieldNum, type: BaseType.UINT8.rawValue, scale: 0.7111111, offset: 0, units: "degrees", accumulated: false)
		mesg.fields[SplitMesg.avgRightPowerPhasePeakFieldNum] = Field(name: "AvgRightPowerPhasePeak", num: SplitMesg.avgRightPowerPhasePeakFieldNum, type: BaseType.UINT8.rawValue, scale: 0.7111111, offset: 0, units: "degrees", accumulated: false)
		mesg.fields[SplitMesg.avgPowerPositionFieldNum] = Field(name: "AvgPowerPosition", num: SplitMesg.avgPowerPositionFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitMesg.maxPowerPositionFieldNum] = Field(name: "MaxPowerPosition", num: SplitMesg.maxPowerPositionFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitMesg.avgLeftTorqueEffectivenessFieldNum] = Field(name: "AvgLeftTorqueEffectiveness", num: SplitMesg.avgLeftTorqueEffectivenessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitMesg.avgRightTorqueEffectivenessFieldNum] = Field(name: "AvgRightTorqueEffectiveness", num: SplitMesg.avgRightTorqueEffectivenessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitMesg.avgLeftPedalSmoothnessFieldNum] = Field(name: "AvgLeftPedalSmoothness", num: SplitMesg.avgLeftPedalSmoothnessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitMesg.avgRightPedalSmoothnessFieldNum] = Field(name: "AvgRightPedalSmoothness", num: SplitMesg.avgRightPedalSmoothnessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitMesg.avgCombinedPedalSmoothnessFieldNum] = Field(name: "AvgCombinedPedalSmoothness", num: SplitMesg.avgCombinedPedalSmoothnessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitMesg.avgFlowFieldNum] = Field(name: "AvgFlow", num: SplitMesg.avgFlowFieldNum, type: BaseType.FLOAT32.rawValue, scale: 1, offset: 0, units: "Flow", accumulated: false)
		mesg.fields[SplitMesg.totalGritFieldNum] = Field(name: "TotalGrit", num: SplitMesg.totalGritFieldNum, type: BaseType.FLOAT32.rawValue, scale: 1, offset: 0, units: "kGrit", accumulated: false)
		mesg.fields[SplitMesg.swimStrokeFieldNum] = Field(name: "SwimStroke", num: SplitMesg.swimStrokeFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.numActiveLengthsFieldNum] = Field(name: "NumActiveLengths", num: SplitMesg.numActiveLengthsFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "lengths", accumulated: false)
		mesg.fields[SplitMesg.avgSwolfFieldNum] = Field(name: "AvgSwolf", num: SplitMesg.avgSwolfFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.avgStrokeDistanceFieldNum] = Field(name: "AvgStrokeDistance", num: SplitMesg.avgStrokeDistanceFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitMesg.avgStrokesPerLengthFieldNum] = Field(name: "AvgStrokesPerLength", num: SplitMesg.avgStrokesPerLengthFieldNum, type: BaseType.UINT16.rawValue, scale: 10, offset: 0, units: "strokes / length", accumulated: false)
		mesg.fields[SplitMesg.firstLapIndexFieldNum] = Field(name: "FirstLapIndex", num: SplitMesg.firstLapIndexFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.numLapsFieldNum] = Field(name: "NumLaps", num: SplitMesg.numLapsFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.climbGradingScaleFieldNum] = Field(name: "ClimbGradingScale", num: SplitMesg.climbGradingScaleFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.climbGradeValueFieldNum] = Field(name: "ClimbGradeValue", num: SplitMesg.climbGradeValueFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeYds", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeYds)].addMap(refFieldNum: 69, refFieldValue: 0)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeUiaa", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeUiaa)].addMap(refFieldNum: 69, refFieldValue: 1)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeFrench", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeFrench)].addMap(refFieldNum: 69, refFieldValue: 2)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeBritishAdjectival", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeBritishAdjectival)].addMap(refFieldNum: 69, refFieldValue: 3)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeBritishTechnical", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeBritishTechnical)].addMap(refFieldNum: 69, refFieldValue: 4)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeEwbank", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeEwbank)].addMap(refFieldNum: 69, refFieldValue: 5)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeBrazilian", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeBrazilian)].addMap(refFieldNum: 69, refFieldValue: 6)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeSaxon", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeSaxon)].addMap(refFieldNum: 69, refFieldValue: 7)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeVermin", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeVermin)].addMap(refFieldNum: 69, refFieldValue: 8)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeFont", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeFont)].addMap(refFieldNum: 69, refFieldValue: 9)
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbGradeDankyu", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitMesg.climbGradeValueFieldNum]?.subFields[Int(ClimbGradeValueSubField.climbGradeDankyu)].addMap(refFieldNum: 69, refFieldValue: 10)
		mesg.fields[SplitMesg.statusFieldNum] = Field(name: "Status", num: SplitMesg.statusFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.numFallsFieldNum] = Field(name: "NumFalls", num: SplitMesg.numFallsFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.climbSendFieldNum] = Field(name: "ClimbSend", num: SplitMesg.climbSendFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.startElevationFieldNum] = Field(name: "StartElevation", num: SplitMesg.startElevationFieldNum, type: BaseType.UINT32.rawValue, scale: 5, offset: 500, units: "m", accumulated: false)
		mesg.fields[SplitMesg.activeTimeFieldNum] = Field(name: "ActiveTime", num: SplitMesg.activeTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.metabolicCaloriesFieldNum] = Field(name: "MetabolicCalories", num: SplitMesg.metabolicCaloriesFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "kcal", accumulated: false)
		mesg.fields[SplitMesg.totalFractionalAscentFieldNum] = Field(name: "TotalFractionalAscent", num: SplitMesg.totalFractionalAscentFieldNum, type: BaseType.UINT8.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitMesg.totalFractionalDescentFieldNum] = Field(name: "TotalFractionalDescent", num: SplitMesg.totalFractionalDescentFieldNum, type: BaseType.UINT8.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitMesg.avgGradeFieldNum] = Field(name: "AvgGrade", num: SplitMesg.avgGradeFieldNum, type: BaseType.SINT16.rawValue, scale: 100, offset: 0, units: "%", accumulated: false)
		mesg.fields[SplitMesg.maxGradeFieldNum] = Field(name: "MaxGrade", num: SplitMesg.maxGradeFieldNum, type: BaseType.SINT16.rawValue, scale: 100, offset: 0, units: "%", accumulated: false)
		mesg.fields[SplitMesg.minCadenceFieldNum] = Field(name: "MinCadence", num: SplitMesg.minCadenceFieldNum, type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "rpm", accumulated: false)
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields.append(SubField(name: "MinRunningCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strides/min"))
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields[Int(MinCadenceSubField.minRunningCadence)].addMap(refFieldNum: 11, refFieldValue: 1)
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields.append(SubField(name: "MinSwimmingCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields[Int(MinCadenceSubField.minSwimmingCadence)].addMap(refFieldNum: 11, refFieldValue: 5)
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields.append(SubField(name: "MinPaddlesportCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields[Int(MinCadenceSubField.minPaddlesportCadence)].addMap(refFieldNum: 11, refFieldValue: 15)
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields[Int(MinCadenceSubField.minPaddlesportCadence)].addMap(refFieldNum: 11, refFieldValue: 37)
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields.append(SubField(name: "MinPushCadence", type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "pushes/min"))
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields[Int(MinCadenceSubField.minPushCadence)].addMap(refFieldNum: 11, refFieldValue: 66)
        mesg.fields[SplitMesg.minCadenceFieldNum]?.subFields[Int(MinCadenceSubField.minPushCadence)].addMap(refFieldNum: 11, refFieldValue: 65)
		mesg.fields[SplitMesg.avgGradeAdjustedSpeedFieldNum] = Field(name: "AvgGradeAdjustedSpeed", num: SplitMesg.avgGradeAdjustedSpeedFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.avgStressFieldNum] = Field(name: "AvgStress", num: SplitMesg.avgStressFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.avgVamFieldNum] = Field(name: "AvgVam", num: SplitMesg.avgVamFieldNum, type: BaseType.UINT16.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.jumpCountFieldNum] = Field(name: "JumpCount", num: SplitMesg.jumpCountFieldNum, type: BaseType.UINT8.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.totalMovingTimeFieldNum] = Field(name: "TotalMovingTime", num: SplitMesg.totalMovingTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.diveSectionTypeFieldNum] = Field(name: "DiveSectionType", num: SplitMesg.diveSectionTypeFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.avgAscentRateFieldNum] = Field(name: "AvgAscentRate", num: SplitMesg.avgAscentRateFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.maxAscentRateFieldNum] = Field(name: "MaxAscentRate", num: SplitMesg.maxAscentRateFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.avgDescentRateFieldNum] = Field(name: "AvgDescentRate", num: SplitMesg.avgDescentRateFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.maxDescentRateFieldNum] = Field(name: "MaxDescentRate", num: SplitMesg.maxDescentRateFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitMesg.totalAscentTimeFieldNum] = Field(name: "TotalAscentTime", num: SplitMesg.totalAscentTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.totalDescentTimeFieldNum] = Field(name: "TotalDescentTime", num: SplitMesg.totalDescentTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.totalHangTimeFieldNum] = Field(name: "TotalHangTime", num: SplitMesg.totalHangTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.apneaDisciplineFieldNum] = Field(name: "ApneaDiscipline", num: SplitMesg.apneaDisciplineFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.avgDepthFieldNum] = Field(name: "AvgDepth", num: SplitMesg.avgDepthFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitMesg.maxDepthFieldNum] = Field(name: "MaxDepth", num: SplitMesg.maxDepthFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitMesg.minHeartRateFieldNum] = Field(name: "MinHeartRate", num: SplitMesg.minHeartRateFieldNum, type: BaseType.UINT8.rawValue, scale: 1, offset: 0, units: "bpm", accumulated: false)
		mesg.fields[SplitMesg.surfaceIntervalFieldNum] = Field(name: "SurfaceInterval", num: SplitMesg.surfaceIntervalFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitMesg.totalFractionalCyclesFieldNum] = Field(name: "TotalFractionalCycles", num: SplitMesg.totalFractionalCyclesFieldNum, type: BaseType.UINT8.rawValue, scale: 128, offset: 0, units: "cycles", accumulated: false)
		mesg.fields[SplitMesg.avgStanceTimePercentFieldNum] = Field(name: "AvgStanceTimePercent", num: SplitMesg.avgStanceTimePercentFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitMesg.totalAnaerobicTrainingEffectFieldNum] = Field(name: "TotalAnaerobicTrainingEffect", num: SplitMesg.totalAnaerobicTrainingEffectFieldNum, type: BaseType.UINT8.rawValue, scale: 10, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.frontGearShiftCountFieldNum] = Field(name: "FrontGearShiftCount", num: SplitMesg.frontGearShiftCountFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitMesg.rearGearShiftCountFieldNum] = Field(name: "RearGearShiftCount", num: SplitMesg.rearGearShiftCountFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
        return mesg
    }
}