/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.218.0Release
// Tag = production/release/21.218.0-0-g96fee6d7
/////////////////////////////////////////////////////////////////////////////////////////////


open class SplitSummaryMesg : Mesg {
    public static let messageIndexFieldNum:UInt8 = 254
    public static let timestampFieldNum:UInt8 = 253
    public static let splitTypeFieldNum:UInt8 = 0
    public static let sportFieldNum:UInt8 = 1
    public static let subSportFieldNum:UInt8 = 2
    public static let numSplitsFieldNum:UInt8 = 3
    public static let totalTimerTimeFieldNum:UInt8 = 4
    public static let totalDistanceFieldNum:UInt8 = 5
    public static let avgSpeedFieldNum:UInt8 = 6
    public static let maxSpeedFieldNum:UInt8 = 7
    public static let totalAscentFieldNum:UInt8 = 8
    public static let totalDescentFieldNum:UInt8 = 9
    public static let avgHeartRateFieldNum:UInt8 = 10
    public static let maxHeartRateFieldNum:UInt8 = 11
    public static let avgVertSpeedFieldNum:UInt8 = 12
    public static let totalCaloriesFieldNum:UInt8 = 13
    public static let avgCadenceFieldNum:UInt8 = 14
    public static let maxCadenceFieldNum:UInt8 = 15
    public static let totalCyclesFieldNum:UInt8 = 16
    public static let avgTemperatureFieldNum:UInt8 = 17
    public static let maxTemperatureFieldNum:UInt8 = 18
    public static let minTemperatureFieldNum:UInt8 = 19
    public static let avgVerticalOscillationFieldNum:UInt8 = 20
    public static let avgVerticalRatioFieldNum:UInt8 = 21
    public static let avgStanceTimeFieldNum:UInt8 = 22
    public static let avgStanceTimeBalanceFieldNum:UInt8 = 23
    public static let avgStepLengthFieldNum:UInt8 = 24
    public static let avgPowerFieldNum:UInt8 = 25
    public static let maxPowerFieldNum:UInt8 = 26
    public static let normalizedPowerFieldNum:UInt8 = 27
    public static let leftRightBalanceFieldNum:UInt8 = 28
    public static let timeStandingFieldNum:UInt8 = 29
    public static let avgLeftPcoFieldNum:UInt8 = 30
    public static let avgRightPcoFieldNum:UInt8 = 31
    public static let avgLeftPowerPhaseFieldNum:UInt8 = 32
    public static let avgLeftPowerPhasePeakFieldNum:UInt8 = 33
    public static let avgRightPowerPhaseFieldNum:UInt8 = 34
    public static let avgRightPowerPhasePeakFieldNum:UInt8 = 35
    public static let avgPowerPositionFieldNum:UInt8 = 36
    public static let maxPowerPositionFieldNum:UInt8 = 37
    public static let avgLeftTorqueEffectivenessFieldNum:UInt8 = 38
    public static let avgRightTorqueEffectivenessFieldNum:UInt8 = 39
    public static let avgLeftPedalSmoothnessFieldNum:UInt8 = 40
    public static let avgRightPedalSmoothnessFieldNum:UInt8 = 41
    public static let avgCombinedPedalSmoothnessFieldNum:UInt8 = 42
    public static let avgFlowFieldNum:UInt8 = 43
    public static let totalGritFieldNum:UInt8 = 44
    public static let swimStrokeFieldNum:UInt8 = 47
    public static let numActiveLengthsFieldNum:UInt8 = 48
    public static let avgSwolfFieldNum:UInt8 = 49
    public static let avgStrokeDistanceFieldNum:UInt8 = 50
    public static let avgStrokesPerLengthFieldNum:UInt8 = 51
    public static let avgAscentFieldNum:UInt8 = 52
    public static let maxAscentFieldNum:UInt8 = 53
    public static let climbGradingScaleFieldNum:UInt8 = 54
    public static let climbMaxGradeValueFieldNum:UInt8 = 55
    public static let numFallsFieldNum:UInt8 = 56
    public static let numClimbsAttemptedFieldNum:UInt8 = 58
    public static let numClimbsCompletedFieldNum:UInt8 = 59
    public static let maxDistanceFieldNum:UInt8 = 60
    public static let metabolicCaloriesFieldNum:UInt8 = 64
    public static let activeTimeFieldNum:UInt8 = 65
    public static let totalFractionalAscentFieldNum:UInt8 = 66
    public static let totalFractionalDescentFieldNum:UInt8 = 67
    public static let avgFractionalAscentFieldNum:UInt8 = 68
    public static let maxFractionalAscentFieldNum:UInt8 = 69
    public static let avgGradeAdjustedSpeedFieldNum:UInt8 = 71
    public static let avgStressFieldNum:UInt8 = 72
    public static let totalMovingTimeFieldNum:UInt8 = 77
    public static let startTimeFieldNum:UInt8 = 79
    public static let minHeartRateFieldNum:UInt8 = 87
    public static let avgStanceTimePercentFieldNum:UInt8 = 91
    public static let maxTotalTimerTimeFieldNum:UInt8 = 101

	private struct AvgCadenceSubField {
        public static let avgRunningCadence:UInt16 = 0
        public static let avgSwimmingCadence:UInt16 = 1
        public static let avgPaddlesportCadence:UInt16 = 2
        public static let avgPushCadence:UInt16 = 3
        public static let subfields:UInt16 = 4
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	private struct MaxCadenceSubField {
        public static let maxRunningCadence:UInt16 = 0
        public static let maxSwimmingCadence:UInt16 = 1
        public static let maxPaddlesportCadence:UInt16 = 2
        public static let maxPushCadence:UInt16 = 3
        public static let subfields:UInt16 = 4
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	private struct TotalCyclesSubField {
        public static let totalStrides:UInt16 = 0
        public static let totalStrokes:UInt16 = 1
        public static let totalReps:UInt16 = 2
        public static let totalPushes:UInt16 = 3
        public static let subfields:UInt16 = 4
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	private struct ClimbMaxGradeValueSubField {
        public static let climbMaxGradeYds:UInt16 = 0
        public static let climbMaxGradeUiaa:UInt16 = 1
        public static let climbMaxGradeFrench:UInt16 = 2
        public static let climbMaxGradeBritishAdjectival:UInt16 = 3
        public static let climbMaxGradeBritishTechnical:UInt16 = 4
        public static let climbMaxGradeEwbank:UInt16 = 5
        public static let climbMaxGradeBrazilian:UInt16 = 6
        public static let climbMaxGradeSaxon:UInt16 = 7
        public static let climbMaxGradeVermin:UInt16 = 8
        public static let climbMaxGradeFont:UInt16 = 9
        public static let climbMaxGradeDankyu:UInt16 = 10
        public static let subfields:UInt16 = 11
        public static let active:UInt16 = FIT.SUBFIELD_INDEX.ACTIVE_SUBFIELD
        public static let mainField:UInt16 = FIT.SUBFIELD_INDEX.MAIN_FIELD
    }

	public init() {
        super.init(mesg: SplitSummaryMesg.createSplitSummaryMesg())
    }

    public override init(mesg: Mesg) {
        super.init(mesg: mesg)
    }

    fileprivate override init(name: String, num: UInt16) {
        super.init(name: name, num: num)
    }

	public func getMessageIndex() -> MessageIndex? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.messageIndexFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMessageIndex(_ value: MessageIndex) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.messageIndexFieldNum, value: value)
	}

	public func getTimestamp() -> DateTime? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.timestampFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setTimestamp(_ value: DateTime) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.timestampFieldNum, value: value.timestamp)
	}

	public func getSplitType() -> SplitType? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.splitTypeFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return SplitType(rawValue: value) ?? .invalid
	}

	public func setSplitType(_ value: SplitType) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.splitTypeFieldNum, value: value.rawValue)
	}

	public func getSport() -> Sport? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.sportFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return Sport(rawValue: value) ?? .invalid
	}

	public func setSport(_ value: Sport) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.sportFieldNum, value: value.rawValue)
	}

	public func getSubSport() -> SubSport? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.subSportFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return SubSport(rawValue: value) ?? .invalid
	}

	public func setSubSport(_ value: SubSport) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.subSportFieldNum, value: value.rawValue)
	}

	public func getNumSplits() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.numSplitsFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNumSplits(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.numSplitsFieldNum, value: value)
	}

	public func getTotalTimerTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalTimerTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalTimerTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalTimerTimeFieldNum, value: value)
	}

	public func getTotalDistance() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalDistanceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalDistance(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalDistanceFieldNum, value: value)
	}

	public func getAvgSpeed() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgSpeedFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgSpeed(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgSpeedFieldNum, value: value)
	}

	public func getMaxSpeed() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxSpeedFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxSpeed(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxSpeedFieldNum, value: value)
	}

	public func getTotalAscent() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalAscentFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setTotalAscent(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalAscentFieldNum, value: value)
	}

	public func getTotalDescent() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalDescentFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setTotalDescent(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalDescentFieldNum, value: value)
	}

	public func getAvgHeartRate() -> UInt8? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgHeartRateFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value
	}

	public func setAvgHeartRate(_ value: UInt8) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgHeartRateFieldNum, value: value)
	}

	public func getMaxHeartRate() -> UInt8? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxHeartRateFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value
	}

	public func setMaxHeartRate(_ value: UInt8) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxHeartRateFieldNum, value: value)
	}

	public func getAvgVertSpeed() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgVertSpeedFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgVertSpeed(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgVertSpeedFieldNum, value: value)
	}

	public func getTotalCalories() -> UInt32? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalCaloriesFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return value
	}

	public func setTotalCalories(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalCaloriesFieldNum, value: value)
	}

	public func getAvgCadence() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, value: value)
	}

	public func getAvgRunningCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, index: 0, subFieldIndex: AvgCadenceSubField.avgRunningCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setAvgRunningCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, value: value, index: 0, subFieldIndex: AvgCadenceSubField.avgRunningCadence )
	}

	public func getAvgSwimmingCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, index: 0, subFieldIndex: AvgCadenceSubField.avgSwimmingCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setAvgSwimmingCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, value: value, index: 0, subFieldIndex: AvgCadenceSubField.avgSwimmingCadence )
	}

	public func getAvgPaddlesportCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, index: 0, subFieldIndex: AvgCadenceSubField.avgPaddlesportCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setAvgPaddlesportCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, value: value, index: 0, subFieldIndex: AvgCadenceSubField.avgPaddlesportCadence )
	}

	public func getAvgPushCadence() throws -> UInt16? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, index: 0, subFieldIndex: AvgCadenceSubField.avgPushCadence).map({UInt16(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setAvgPushCadence(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgCadenceFieldNum, value: value, index: 0, subFieldIndex: AvgCadenceSubField.avgPushCadence )
	}

	public func getMaxCadence() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, value: value)
	}

	public func getMaxRunningCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, index: 0, subFieldIndex: MaxCadenceSubField.maxRunningCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMaxRunningCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, value: value, index: 0, subFieldIndex: MaxCadenceSubField.maxRunningCadence )
	}

	public func getMaxSwimmingCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, index: 0, subFieldIndex: MaxCadenceSubField.maxSwimmingCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMaxSwimmingCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, value: value, index: 0, subFieldIndex: MaxCadenceSubField.maxSwimmingCadence )
	}

	public func getMaxPaddlesportCadence() throws -> Float64? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, index: 0, subFieldIndex: MaxCadenceSubField.maxPaddlesportCadence).map({Float64(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMaxPaddlesportCadence(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, value: value, index: 0, subFieldIndex: MaxCadenceSubField.maxPaddlesportCadence )
	}

	public func getMaxPushCadence() throws -> UInt16? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, index: 0, subFieldIndex: MaxCadenceSubField.maxPushCadence).map({UInt16(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setMaxPushCadence(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxCadenceFieldNum, value: value, index: 0, subFieldIndex: MaxCadenceSubField.maxPushCadence )
	}

	public func getTotalCycles() -> UInt32? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return value
	}

	public func setTotalCycles(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, value: value)
	}

	public func getTotalStrides() throws -> UInt32? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, index: 0, subFieldIndex: TotalCyclesSubField.totalStrides).map({UInt32(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setTotalStrides(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, value: value, index: 0, subFieldIndex: TotalCyclesSubField.totalStrides )
	}

	public func getTotalStrokes() throws -> UInt32? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, index: 0, subFieldIndex: TotalCyclesSubField.totalStrokes).map({UInt32(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setTotalStrokes(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, value: value, index: 0, subFieldIndex: TotalCyclesSubField.totalStrokes )
	}

	public func getTotalReps() throws -> UInt32? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, index: 0, subFieldIndex: TotalCyclesSubField.totalReps).map({UInt32(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setTotalReps(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, value: value, index: 0, subFieldIndex: TotalCyclesSubField.totalReps )
	}

	public func getTotalPushes() throws -> UInt32? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, index: 0, subFieldIndex: TotalCyclesSubField.totalPushes).map({UInt32(fitValue: $0)}) else {
			return nil
		}
		
		return value
	}

	public func setTotalPushes(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalCyclesFieldNum, value: value, index: 0, subFieldIndex: TotalCyclesSubField.totalPushes )
	}

	public func getAvgTemperature() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgTemperatureFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setAvgTemperature(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgTemperatureFieldNum, value: value)
	}

	public func getMaxTemperature() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxTemperatureFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setMaxTemperature(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxTemperatureFieldNum, value: value)
	}

	public func getMinTemperature() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.minTemperatureFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setMinTemperature(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.minTemperatureFieldNum, value: value)
	}

	public func getAvgVerticalOscillation() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgVerticalOscillationFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgVerticalOscillation(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgVerticalOscillationFieldNum, value: value)
	}

	public func getAvgVerticalRatio() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgVerticalRatioFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgVerticalRatio(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgVerticalRatioFieldNum, value: value)
	}

	public func getAvgStanceTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgStanceTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStanceTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgStanceTimeFieldNum, value: value)
	}

	public func getAvgStanceTimeBalance() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgStanceTimeBalanceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStanceTimeBalance(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgStanceTimeBalanceFieldNum, value: value)
	}

	public func getAvgStepLength() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgStepLengthFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStepLength(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgStepLengthFieldNum, value: value)
	}

	public func getAvgPower() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgPowerFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgPower(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgPowerFieldNum, value: value)
	}

	public func getMaxPower() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxPowerFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMaxPower(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxPowerFieldNum, value: value)
	}

	public func getNormalizedPower() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.normalizedPowerFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNormalizedPower(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.normalizedPowerFieldNum, value: value)
	}

	public func getLeftRightBalance() -> LeftRightBalance100? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.leftRightBalanceFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setLeftRightBalance(_ value: LeftRightBalance100) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.leftRightBalanceFieldNum, value: value)
	}

	public func getTimeStanding() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.timeStandingFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTimeStanding(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.timeStandingFieldNum, value: value)
	}

	public func getAvgLeftPco() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgLeftPcoFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setAvgLeftPco(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgLeftPcoFieldNum, value: value)
	}

	public func getAvgRightPco() -> Int8? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgRightPcoFieldNum, index:0) as? Int8 else {
            return nil
        }
		return value
	}

	public func setAvgRightPco(_ value: Int8) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgRightPcoFieldNum, value: value)
	}

	public func getNumAvgLeftPowerPhase() -> UInt8 {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgLeftPowerPhaseFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgLeftPowerPhase() -> [Float64?]? {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgLeftPowerPhaseFieldNum) else {
			return nil
		}
		return field.toArray() as [Float64?]
	}

	public func getAvgLeftPowerPhase(index: Int) -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgLeftPowerPhaseFieldNum, index: index) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgLeftPowerPhase(index: Int, value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgLeftPowerPhaseFieldNum, value: value, index: index)
	}

	public func getNumAvgLeftPowerPhasePeak() -> UInt8 {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgLeftPowerPhasePeakFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgLeftPowerPhasePeak() -> [Float64?]? {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgLeftPowerPhasePeakFieldNum) else {
			return nil
		}
		return field.toArray() as [Float64?]
	}

	public func getAvgLeftPowerPhasePeak(index: Int) -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgLeftPowerPhasePeakFieldNum, index: index) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgLeftPowerPhasePeak(index: Int, value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgLeftPowerPhasePeakFieldNum, value: value, index: index)
	}

	public func getNumAvgRightPowerPhase() -> UInt8 {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgRightPowerPhaseFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgRightPowerPhase() -> [Float64?]? {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgRightPowerPhaseFieldNum) else {
			return nil
		}
		return field.toArray() as [Float64?]
	}

	public func getAvgRightPowerPhase(index: Int) -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgRightPowerPhaseFieldNum, index: index) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgRightPowerPhase(index: Int, value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgRightPowerPhaseFieldNum, value: value, index: index)
	}

	public func getNumAvgRightPowerPhasePeak() -> UInt8 {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgRightPowerPhasePeakFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgRightPowerPhasePeak() -> [Float64?]? {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgRightPowerPhasePeakFieldNum) else {
			return nil
		}
		return field.toArray() as [Float64?]
	}

	public func getAvgRightPowerPhasePeak(index: Int) -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgRightPowerPhasePeakFieldNum, index: index) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgRightPowerPhasePeak(index: Int, value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgRightPowerPhasePeakFieldNum, value: value, index: index)
	}

	public func getNumAvgPowerPosition() -> UInt8 {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgPowerPositionFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getAvgPowerPosition() -> [UInt16?]? {
		guard let field = getField(fieldNum: SplitSummaryMesg.avgPowerPositionFieldNum) else {
			return nil
		}
		return field.toArray() as [UInt16?]
	}

	public func getAvgPowerPosition(index: Int) -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgPowerPositionFieldNum, index: index) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgPowerPosition(index: Int, value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgPowerPositionFieldNum, value: value, index: index)
	}

	public func getNumMaxPowerPosition() -> UInt8 {
		guard let field = getField(fieldNum: SplitSummaryMesg.maxPowerPositionFieldNum) else {
			return 0
		}

		return field.numValues
	}

	public func getMaxPowerPosition() -> [UInt16?]? {
		guard let field = getField(fieldNum: SplitSummaryMesg.maxPowerPositionFieldNum) else {
			return nil
		}
		return field.toArray() as [UInt16?]
	}

	public func getMaxPowerPosition(index: Int) -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxPowerPositionFieldNum, index: index) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMaxPowerPosition(index: Int, value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxPowerPositionFieldNum, value: value, index: index)
	}

	public func getAvgLeftTorqueEffectiveness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgLeftTorqueEffectivenessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgLeftTorqueEffectiveness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgLeftTorqueEffectivenessFieldNum, value: value)
	}

	public func getAvgRightTorqueEffectiveness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgRightTorqueEffectivenessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgRightTorqueEffectiveness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgRightTorqueEffectivenessFieldNum, value: value)
	}

	public func getAvgLeftPedalSmoothness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgLeftPedalSmoothnessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgLeftPedalSmoothness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgLeftPedalSmoothnessFieldNum, value: value)
	}

	public func getAvgRightPedalSmoothness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgRightPedalSmoothnessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgRightPedalSmoothness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgRightPedalSmoothnessFieldNum, value: value)
	}

	public func getAvgCombinedPedalSmoothness() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgCombinedPedalSmoothnessFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgCombinedPedalSmoothness(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgCombinedPedalSmoothnessFieldNum, value: value)
	}

	public func getAvgFlow() -> Float32? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgFlowFieldNum, index:0) as? Float32 else {
            return nil
        }
		return value
	}

	public func setAvgFlow(_ value: Float32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgFlowFieldNum, value: value)
	}

	public func getTotalGrit() -> Float32? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalGritFieldNum, index:0) as? Float32 else {
            return nil
        }
		return value
	}

	public func setTotalGrit(_ value: Float32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalGritFieldNum, value: value)
	}

	public func getSwimStroke() -> SwimStroke? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.swimStrokeFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return SwimStroke(rawValue: value) ?? .invalid
	}

	public func setSwimStroke(_ value: SwimStroke) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.swimStrokeFieldNum, value: value.rawValue)
	}

	public func getNumActiveLengths() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.numActiveLengthsFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNumActiveLengths(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.numActiveLengthsFieldNum, value: value)
	}

	public func getAvgSwolf() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgSwolfFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgSwolf(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgSwolfFieldNum, value: value)
	}

	public func getAvgStrokeDistance() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgStrokeDistanceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStrokeDistance(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgStrokeDistanceFieldNum, value: value)
	}

	public func getAvgStrokesPerLength() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgStrokesPerLengthFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStrokesPerLength(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgStrokesPerLengthFieldNum, value: value)
	}

	public func getAvgAscent() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgAscentFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgAscent(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgAscentFieldNum, value: value)
	}

	public func getMaxAscent() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxAscentFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMaxAscent(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxAscentFieldNum, value: value)
	}

	public func getClimbGradingScale() -> ClimbGradingScale? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.climbGradingScaleFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return ClimbGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbGradingScale(_ value: ClimbGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbGradingScaleFieldNum, value: value.rawValue)
	}

	public func getClimbMaxGradeValue() -> UInt32? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return value
	}

	public func setClimbMaxGradeValue(_ value: UInt32) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value)
	}

	public func getClimbMaxGradeYds() throws -> YdsGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeYds).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return YdsGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeYds(_ value: YdsGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeYds )
	}

	public func getClimbMaxGradeUiaa() throws -> UiaaGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeUiaa).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return UiaaGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeUiaa(_ value: UiaaGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeUiaa )
	}

	public func getClimbMaxGradeFrench() throws -> FrenchGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeFrench).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return FrenchGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeFrench(_ value: FrenchGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeFrench )
	}

	public func getClimbMaxGradeBritishAdjectival() throws -> BritishAdjectivalGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeBritishAdjectival).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return BritishAdjectivalGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeBritishAdjectival(_ value: BritishAdjectivalGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeBritishAdjectival )
	}

	public func getClimbMaxGradeBritishTechnical() throws -> BritishTechnicalGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeBritishTechnical).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return BritishTechnicalGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeBritishTechnical(_ value: BritishTechnicalGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeBritishTechnical )
	}

	public func getClimbMaxGradeEwbank() throws -> EwbankGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeEwbank).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return EwbankGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeEwbank(_ value: EwbankGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeEwbank )
	}

	public func getClimbMaxGradeBrazilian() throws -> BrazilianGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeBrazilian).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return BrazilianGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeBrazilian(_ value: BrazilianGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeBrazilian )
	}

	public func getClimbMaxGradeSaxon() throws -> SaxonGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeSaxon).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return SaxonGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeSaxon(_ value: SaxonGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeSaxon )
	}

	public func getClimbMaxGradeVermin() throws -> VerminGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeVermin).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return VerminGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeVermin(_ value: VerminGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeVermin )
	}

	public func getClimbMaxGradeFont() throws -> FontGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeFont).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return FontGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeFont(_ value: FontGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeFont )
	}

	public func getClimbMaxGradeDankyu() throws -> DankyuGradingScale? {
		guard let value = try getFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeDankyu).map({UInt8(fitValue: $0)}) else {
			return nil
		}
		
		return DankyuGradingScale(rawValue: value) ?? .invalid
	}

	public func setClimbMaxGradeDankyu(_ value: DankyuGradingScale) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.climbMaxGradeValueFieldNum, value: value.rawValue, index: 0, subFieldIndex: ClimbMaxGradeValueSubField.climbMaxGradeDankyu )
	}

	public func getNumFalls() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.numFallsFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNumFalls(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.numFallsFieldNum, value: value)
	}

	public func getNumClimbsAttempted() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.numClimbsAttemptedFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNumClimbsAttempted(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.numClimbsAttemptedFieldNum, value: value)
	}

	public func getNumClimbsCompleted() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.numClimbsCompletedFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setNumClimbsCompleted(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.numClimbsCompletedFieldNum, value: value)
	}

	public func getMaxDistance() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxDistanceFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxDistance(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxDistanceFieldNum, value: value)
	}

	public func getMetabolicCalories() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.metabolicCaloriesFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMetabolicCalories(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.metabolicCaloriesFieldNum, value: value)
	}

	public func getActiveTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.activeTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setActiveTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.activeTimeFieldNum, value: value)
	}

	public func getTotalFractionalAscent() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalFractionalAscentFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalFractionalAscent(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalFractionalAscentFieldNum, value: value)
	}

	public func getTotalFractionalDescent() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalFractionalDescentFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalFractionalDescent(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalFractionalDescentFieldNum, value: value)
	}

	public func getAvgFractionalAscent() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgFractionalAscentFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgFractionalAscent(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgFractionalAscentFieldNum, value: value)
	}

	public func getMaxFractionalAscent() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxFractionalAscentFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxFractionalAscent(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxFractionalAscentFieldNum, value: value)
	}

	public func getAvgGradeAdjustedSpeed() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgGradeAdjustedSpeedFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgGradeAdjustedSpeed(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgGradeAdjustedSpeedFieldNum, value: value)
	}

	public func getAvgStress() -> UInt16? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgStressFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setAvgStress(_ value: UInt16) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgStressFieldNum, value: value)
	}

	public func getTotalMovingTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.totalMovingTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setTotalMovingTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.totalMovingTimeFieldNum, value: value)
	}

	public func getStartTime() -> DateTime? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.startTimeFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setStartTime(_ value: DateTime) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.startTimeFieldNum, value: value.timestamp)
	}

	public func getMinHeartRate() -> UInt8? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.minHeartRateFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return value
	}

	public func setMinHeartRate(_ value: UInt8) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.minHeartRateFieldNum, value: value)
	}

	public func getAvgStanceTimePercent() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.avgStanceTimePercentFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setAvgStanceTimePercent(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.avgStanceTimePercentFieldNum, value: value)
	}

	public func getMaxTotalTimerTime() -> Float64? {
		guard let value = getFieldValue(fieldNum: SplitSummaryMesg.maxTotalTimerTimeFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setMaxTotalTimerTime(_ value: Float64) throws {
		try setFieldValue(fieldNum: SplitSummaryMesg.maxTotalTimerTimeFieldNum, value: value)
	}

	public class func createSplitSummaryMesg() -> SplitSummaryMesg {
        let mesg = SplitSummaryMesg(name: "SplitSummary", num: Profile.MesgNum.splitSummary)
		
		mesg.fields[SplitSummaryMesg.messageIndexFieldNum] = Field(name: "MessageIndex", num: SplitSummaryMesg.messageIndexFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.timestampFieldNum] = Field(name: "Timestamp", num: SplitSummaryMesg.timestampFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitSummaryMesg.splitTypeFieldNum] = Field(name: "SplitType", num: SplitSummaryMesg.splitTypeFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.sportFieldNum] = Field(name: "Sport", num: SplitSummaryMesg.sportFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.subSportFieldNum] = Field(name: "SubSport", num: SplitSummaryMesg.subSportFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.numSplitsFieldNum] = Field(name: "NumSplits", num: SplitSummaryMesg.numSplitsFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalTimerTimeFieldNum] = Field(name: "TotalTimerTime", num: SplitSummaryMesg.totalTimerTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalDistanceFieldNum] = Field(name: "TotalDistance", num: SplitSummaryMesg.totalDistanceFieldNum, type: BaseType.UINT32.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgSpeedFieldNum] = Field(name: "AvgSpeed", num: SplitSummaryMesg.avgSpeedFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxSpeedFieldNum] = Field(name: "MaxSpeed", num: SplitSummaryMesg.maxSpeedFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalAscentFieldNum] = Field(name: "TotalAscent", num: SplitSummaryMesg.totalAscentFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalDescentFieldNum] = Field(name: "TotalDescent", num: SplitSummaryMesg.totalDescentFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgHeartRateFieldNum] = Field(name: "AvgHeartRate", num: SplitSummaryMesg.avgHeartRateFieldNum, type: BaseType.UINT8.rawValue, scale: 1, offset: 0, units: "bpm", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxHeartRateFieldNum] = Field(name: "MaxHeartRate", num: SplitSummaryMesg.maxHeartRateFieldNum, type: BaseType.UINT8.rawValue, scale: 1, offset: 0, units: "bpm", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgVertSpeedFieldNum] = Field(name: "AvgVertSpeed", num: SplitSummaryMesg.avgVertSpeedFieldNum, type: BaseType.SINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalCaloriesFieldNum] = Field(name: "TotalCalories", num: SplitSummaryMesg.totalCaloriesFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "kcal", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgCadenceFieldNum] = Field(name: "AvgCadence", num: SplitSummaryMesg.avgCadenceFieldNum, type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "rpm", accumulated: false)
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields.append(SubField(name: "AvgRunningCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strides/min"))
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgRunningCadence)].addMap(refFieldNum: 1, refFieldValue: 1)
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields.append(SubField(name: "AvgSwimmingCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgSwimmingCadence)].addMap(refFieldNum: 1, refFieldValue: 5)
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields.append(SubField(name: "AvgPaddlesportCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgPaddlesportCadence)].addMap(refFieldNum: 1, refFieldValue: 15)
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgPaddlesportCadence)].addMap(refFieldNum: 1, refFieldValue: 37)
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields.append(SubField(name: "AvgPushCadence", type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "pushes/min"))
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgPushCadence)].addMap(refFieldNum: 1, refFieldValue: 66)
        mesg.fields[SplitSummaryMesg.avgCadenceFieldNum]?.subFields[Int(AvgCadenceSubField.avgPushCadence)].addMap(refFieldNum: 1, refFieldValue: 65)
		mesg.fields[SplitSummaryMesg.maxCadenceFieldNum] = Field(name: "MaxCadence", num: SplitSummaryMesg.maxCadenceFieldNum, type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "rpm", accumulated: false)
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields.append(SubField(name: "MaxRunningCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strides/min"))
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxRunningCadence)].addMap(refFieldNum: 1, refFieldValue: 1)
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields.append(SubField(name: "MaxSwimmingCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxSwimmingCadence)].addMap(refFieldNum: 1, refFieldValue: 5)
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields.append(SubField(name: "MaxPaddlesportCadence", type: BaseType.UINT16.rawValue, scale: 128, offset: 0, units: "strokes/min"))
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxPaddlesportCadence)].addMap(refFieldNum: 1, refFieldValue: 15)
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxPaddlesportCadence)].addMap(refFieldNum: 1, refFieldValue: 37)
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields.append(SubField(name: "MaxPushCadence", type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "pushes/min"))
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxPushCadence)].addMap(refFieldNum: 1, refFieldValue: 66)
        mesg.fields[SplitSummaryMesg.maxCadenceFieldNum]?.subFields[Int(MaxCadenceSubField.maxPushCadence)].addMap(refFieldNum: 1, refFieldValue: 65)
		mesg.fields[SplitSummaryMesg.totalCyclesFieldNum] = Field(name: "TotalCycles", num: SplitSummaryMesg.totalCyclesFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "cycles", accumulated: false)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields.append(SubField(name: "TotalStrides", type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "strides"))
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrides)].addMap(refFieldNum: 1, refFieldValue: 1)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrides)].addMap(refFieldNum: 1, refFieldValue: 11)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields.append(SubField(name: "TotalStrokes", type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "strokes"))
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrokes)].addMap(refFieldNum: 1, refFieldValue: 2)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrokes)].addMap(refFieldNum: 1, refFieldValue: 5)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrokes)].addMap(refFieldNum: 1, refFieldValue: 15)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalStrokes)].addMap(refFieldNum: 1, refFieldValue: 37)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields.append(SubField(name: "TotalReps", type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "reps"))
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalReps)].addMap(refFieldNum: 1, refFieldValue: 62)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields.append(SubField(name: "TotalPushes", type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "pushes"))
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalPushes)].addMap(refFieldNum: 1, refFieldValue: 66)
        mesg.fields[SplitSummaryMesg.totalCyclesFieldNum]?.subFields[Int(TotalCyclesSubField.totalPushes)].addMap(refFieldNum: 1, refFieldValue: 65)
		mesg.fields[SplitSummaryMesg.avgTemperatureFieldNum] = Field(name: "AvgTemperature", num: SplitSummaryMesg.avgTemperatureFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "C", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxTemperatureFieldNum] = Field(name: "MaxTemperature", num: SplitSummaryMesg.maxTemperatureFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "C", accumulated: false)
		mesg.fields[SplitSummaryMesg.minTemperatureFieldNum] = Field(name: "MinTemperature", num: SplitSummaryMesg.minTemperatureFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "C", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgVerticalOscillationFieldNum] = Field(name: "AvgVerticalOscillation", num: SplitSummaryMesg.avgVerticalOscillationFieldNum, type: BaseType.UINT16.rawValue, scale: 10, offset: 0, units: "mm", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgVerticalRatioFieldNum] = Field(name: "AvgVerticalRatio", num: SplitSummaryMesg.avgVerticalRatioFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgStanceTimeFieldNum] = Field(name: "AvgStanceTime", num: SplitSummaryMesg.avgStanceTimeFieldNum, type: BaseType.UINT16.rawValue, scale: 10, offset: 0, units: "ms", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgStanceTimeBalanceFieldNum] = Field(name: "AvgStanceTimeBalance", num: SplitSummaryMesg.avgStanceTimeBalanceFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgStepLengthFieldNum] = Field(name: "AvgStepLength", num: SplitSummaryMesg.avgStepLengthFieldNum, type: BaseType.UINT16.rawValue, scale: 10, offset: 0, units: "mm", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgPowerFieldNum] = Field(name: "AvgPower", num: SplitSummaryMesg.avgPowerFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxPowerFieldNum] = Field(name: "MaxPower", num: SplitSummaryMesg.maxPowerFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitSummaryMesg.normalizedPowerFieldNum] = Field(name: "NormalizedPower", num: SplitSummaryMesg.normalizedPowerFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitSummaryMesg.leftRightBalanceFieldNum] = Field(name: "LeftRightBalance", num: SplitSummaryMesg.leftRightBalanceFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.timeStandingFieldNum] = Field(name: "TimeStanding", num: SplitSummaryMesg.timeStandingFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgLeftPcoFieldNum] = Field(name: "AvgLeftPco", num: SplitSummaryMesg.avgLeftPcoFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "mm", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgRightPcoFieldNum] = Field(name: "AvgRightPco", num: SplitSummaryMesg.avgRightPcoFieldNum, type: BaseType.SINT8.rawValue, scale: 1, offset: 0, units: "mm", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgLeftPowerPhaseFieldNum] = Field(name: "AvgLeftPowerPhase", num: SplitSummaryMesg.avgLeftPowerPhaseFieldNum, type: BaseType.UINT8.rawValue, scale: 0.7111111, offset: 0, units: "degrees", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgLeftPowerPhasePeakFieldNum] = Field(name: "AvgLeftPowerPhasePeak", num: SplitSummaryMesg.avgLeftPowerPhasePeakFieldNum, type: BaseType.UINT8.rawValue, scale: 0.7111111, offset: 0, units: "degrees", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgRightPowerPhaseFieldNum] = Field(name: "AvgRightPowerPhase", num: SplitSummaryMesg.avgRightPowerPhaseFieldNum, type: BaseType.UINT8.rawValue, scale: 0.7111111, offset: 0, units: "degrees", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgRightPowerPhasePeakFieldNum] = Field(name: "AvgRightPowerPhasePeak", num: SplitSummaryMesg.avgRightPowerPhasePeakFieldNum, type: BaseType.UINT8.rawValue, scale: 0.7111111, offset: 0, units: "degrees", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgPowerPositionFieldNum] = Field(name: "AvgPowerPosition", num: SplitSummaryMesg.avgPowerPositionFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxPowerPositionFieldNum] = Field(name: "MaxPowerPosition", num: SplitSummaryMesg.maxPowerPositionFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgLeftTorqueEffectivenessFieldNum] = Field(name: "AvgLeftTorqueEffectiveness", num: SplitSummaryMesg.avgLeftTorqueEffectivenessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgRightTorqueEffectivenessFieldNum] = Field(name: "AvgRightTorqueEffectiveness", num: SplitSummaryMesg.avgRightTorqueEffectivenessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgLeftPedalSmoothnessFieldNum] = Field(name: "AvgLeftPedalSmoothness", num: SplitSummaryMesg.avgLeftPedalSmoothnessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgRightPedalSmoothnessFieldNum] = Field(name: "AvgRightPedalSmoothness", num: SplitSummaryMesg.avgRightPedalSmoothnessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgCombinedPedalSmoothnessFieldNum] = Field(name: "AvgCombinedPedalSmoothness", num: SplitSummaryMesg.avgCombinedPedalSmoothnessFieldNum, type: BaseType.UINT8.rawValue, scale: 2, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgFlowFieldNum] = Field(name: "AvgFlow", num: SplitSummaryMesg.avgFlowFieldNum, type: BaseType.FLOAT32.rawValue, scale: 1, offset: 0, units: "Flow", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalGritFieldNum] = Field(name: "TotalGrit", num: SplitSummaryMesg.totalGritFieldNum, type: BaseType.FLOAT32.rawValue, scale: 1, offset: 0, units: "kGrit", accumulated: false)
		mesg.fields[SplitSummaryMesg.swimStrokeFieldNum] = Field(name: "SwimStroke", num: SplitSummaryMesg.swimStrokeFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.numActiveLengthsFieldNum] = Field(name: "NumActiveLengths", num: SplitSummaryMesg.numActiveLengthsFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "lengths", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgSwolfFieldNum] = Field(name: "AvgSwolf", num: SplitSummaryMesg.avgSwolfFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgStrokeDistanceFieldNum] = Field(name: "AvgStrokeDistance", num: SplitSummaryMesg.avgStrokeDistanceFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgStrokesPerLengthFieldNum] = Field(name: "AvgStrokesPerLength", num: SplitSummaryMesg.avgStrokesPerLengthFieldNum, type: BaseType.UINT16.rawValue, scale: 10, offset: 0, units: "strokes / length", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgAscentFieldNum] = Field(name: "AvgAscent", num: SplitSummaryMesg.avgAscentFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxAscentFieldNum] = Field(name: "MaxAscent", num: SplitSummaryMesg.maxAscentFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.climbGradingScaleFieldNum] = Field(name: "ClimbGradingScale", num: SplitSummaryMesg.climbGradingScaleFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum] = Field(name: "ClimbMaxGradeValue", num: SplitSummaryMesg.climbMaxGradeValueFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeYds", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeYds)].addMap(refFieldNum: 54, refFieldValue: 0)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeUiaa", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeUiaa)].addMap(refFieldNum: 54, refFieldValue: 1)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeFrench", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeFrench)].addMap(refFieldNum: 54, refFieldValue: 2)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeBritishAdjectival", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeBritishAdjectival)].addMap(refFieldNum: 54, refFieldValue: 3)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeBritishTechnical", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeBritishTechnical)].addMap(refFieldNum: 54, refFieldValue: 4)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeEwbank", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeEwbank)].addMap(refFieldNum: 54, refFieldValue: 5)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeBrazilian", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeBrazilian)].addMap(refFieldNum: 54, refFieldValue: 6)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeSaxon", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeSaxon)].addMap(refFieldNum: 54, refFieldValue: 7)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeVermin", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeVermin)].addMap(refFieldNum: 54, refFieldValue: 8)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeFont", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeFont)].addMap(refFieldNum: 54, refFieldValue: 9)
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields.append(SubField(name: "ClimbMaxGradeDankyu", type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: ""))
        mesg.fields[SplitSummaryMesg.climbMaxGradeValueFieldNum]?.subFields[Int(ClimbMaxGradeValueSubField.climbMaxGradeDankyu)].addMap(refFieldNum: 54, refFieldValue: 10)
		mesg.fields[SplitSummaryMesg.numFallsFieldNum] = Field(name: "NumFalls", num: SplitSummaryMesg.numFallsFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.numClimbsAttemptedFieldNum] = Field(name: "NumClimbsAttempted", num: SplitSummaryMesg.numClimbsAttemptedFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.numClimbsCompletedFieldNum] = Field(name: "NumClimbsCompleted", num: SplitSummaryMesg.numClimbsCompletedFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxDistanceFieldNum] = Field(name: "MaxDistance", num: SplitSummaryMesg.maxDistanceFieldNum, type: BaseType.UINT32.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.metabolicCaloriesFieldNum] = Field(name: "MetabolicCalories", num: SplitSummaryMesg.metabolicCaloriesFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "kcal", accumulated: false)
		mesg.fields[SplitSummaryMesg.activeTimeFieldNum] = Field(name: "ActiveTime", num: SplitSummaryMesg.activeTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalFractionalAscentFieldNum] = Field(name: "TotalFractionalAscent", num: SplitSummaryMesg.totalFractionalAscentFieldNum, type: BaseType.UINT8.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalFractionalDescentFieldNum] = Field(name: "TotalFractionalDescent", num: SplitSummaryMesg.totalFractionalDescentFieldNum, type: BaseType.UINT8.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgFractionalAscentFieldNum] = Field(name: "AvgFractionalAscent", num: SplitSummaryMesg.avgFractionalAscentFieldNum, type: BaseType.UINT8.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxFractionalAscentFieldNum] = Field(name: "MaxFractionalAscent", num: SplitSummaryMesg.maxFractionalAscentFieldNum, type: BaseType.UINT8.rawValue, scale: 100, offset: 0, units: "m", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgGradeAdjustedSpeedFieldNum] = Field(name: "AvgGradeAdjustedSpeed", num: SplitSummaryMesg.avgGradeAdjustedSpeedFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "m/s", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgStressFieldNum] = Field(name: "AvgStress", num: SplitSummaryMesg.avgStressFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.totalMovingTimeFieldNum] = Field(name: "TotalMovingTime", num: SplitSummaryMesg.totalMovingTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
		mesg.fields[SplitSummaryMesg.startTimeFieldNum] = Field(name: "StartTime", num: SplitSummaryMesg.startTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SplitSummaryMesg.minHeartRateFieldNum] = Field(name: "MinHeartRate", num: SplitSummaryMesg.minHeartRateFieldNum, type: BaseType.UINT8.rawValue, scale: 1, offset: 0, units: "bpm", accumulated: false)
		mesg.fields[SplitSummaryMesg.avgStanceTimePercentFieldNum] = Field(name: "AvgStanceTimePercent", num: SplitSummaryMesg.avgStanceTimePercentFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "percent", accumulated: false)
		mesg.fields[SplitSummaryMesg.maxTotalTimerTimeFieldNum] = Field(name: "MaxTotalTimerTime", num: SplitSummaryMesg.maxTotalTimerTimeFieldNum, type: BaseType.UINT32.rawValue, scale: 1000, offset: 0, units: "s", accumulated: false)
        return mesg
    }
}