/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

public enum ApneaDiscipline: UInt8, CaseIterable, Sendable {
    case constantWeightWithFins = 0
    case constantWeightWithBifins = 1
    case constantWeightWithoutFins = 2
    case dynamicWithFins = 3
    case dynamicWithBifins = 4
    case dynamicWithoutFins = 5
    case freeImmersion = 6
    case noLimit = 7
    case speedEnduranceApnea = 8
    case staticApnea = 9
    case variableWeight = 10
    case invalid = 0xFF
}
