/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.218.0Release
// Tag = production/release/21.218.0-0-g96fee6d7
/////////////////////////////////////////////////////////////////////////////////////////////

public enum BrazilianGradingScale: UInt8, CaseIterable, Sendable {
    case _2 = 0
    case _3 = 1
    case _3c = 2
    case _4 = 3
    case _5a = 4
    case _5b = 5
    case _5c = 6
    case _6a = 7
    case _6b = 8
    case _6c = 9
    case _7a = 10
    case _7b = 11
    case _7c = 12
    case _8a = 13
    case _8b = 14
    case _8c = 15
    case _9a = 16
    case _9b = 17
    case _9c = 18
    case _10a = 19
    case _10b = 20
    case _10c = 21
    case _11a = 22
    case _11b = 23
    case _11c = 24
    case _12a = 25
    case _12b = 26
    case invalid = 0xFF
}
