/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

public enum BritishAdjectivalGradingScale: UInt8, CaseIterable, Sendable {
    case m = 0
    case d = 1
    case hD = 2
    case vD = 3
    case mS = 4
    case s = 5
    case hS = 6
    case mVS = 7
    case vS = 8
    case hVS = 9
    case e1 = 10
    case e2 = 11
    case e3 = 12
    case e4 = 13
    case e5 = 14
    case e6 = 15
    case e7 = 16
    case e8 = 17
    case e9 = 18
    case e10 = 19
    case e11 = 20
    case invalid = 0xFF
}
