/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

public enum BritishTechnicalGradingScale: UInt8, CaseIterable, Sendable {
    case _1 = 0
    case _2 = 1
    case _3 = 2
    case _4a = 3
    case _4b = 4
    case _4c = 5
    case _5a = 6
    case _5b = 7
    case _5c = 8
    case _6a = 9
    case _6b = 10
    case _6c = 11
    case _7a = 12
    case _7b = 13
    case _7c = 14
    case invalid = 0xFF
}
