/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.218.0Release
// Tag = production/release/21.218.0-0-g96fee6d7
/////////////////////////////////////////////////////////////////////////////////////////////

public enum ClimbGradingScale: UInt8, CaseIterable, Sendable {
    case yds = 0
    case uiaa = 1
    case french = 2
    case britishAdjectival = 3
    case britishTechnical = 4
    case ewbank = 5
    case brazilian = 6
    case saxon = 7
    case vermin = 8
    case font = 9
    case dankyu = 10
    case ydsPm = 11
    case invalid = 0xFF
}
