/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.202.0Release
// Tag = production/release/21.202.0-0-g9a57aebc
/////////////////////////////////////////////////////////////////////////////////////////////

public enum ClimbProEvent: UInt8, CaseIterable, Sendable {
    case approach = 0
    case start = 1
    case complete = 2
    case invalid = 0xFF
}
