/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.218.0Release
// Tag = production/release/21.218.0-0-g96fee6d7
/////////////////////////////////////////////////////////////////////////////////////////////

public enum DankyuGradingScale: UInt8, CaseIterable, Sendable {
    case _7Kyuu = 0
    case _6Kyuu = 1
    case _5Kyuu = 2
    case _4Kyuu = 3
    case _3Kyuu = 4
    case _2Kyuu = 5
    case _1Kyuu = 6
    case _1Dan = 7
    case _2Dan = 8
    case _3Dan = 9
    case _4Dan = 10
    case _5Dan = 11
    case invalid = 0xFF
}
