/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

public enum EwbankGradingScale: UInt8, CaseIterable, Sendable {
    case _4 = 0
    case _5 = 1
    case _6 = 2
    case _7 = 3
    case _8 = 4
    case _9 = 5
    case _10 = 6
    case _11 = 7
    case _12 = 8
    case _13 = 9
    case _14 = 10
    case _15 = 11
    case _16 = 12
    case _17 = 13
    case _18 = 14
    case _19 = 15
    case _20 = 16
    case _21 = 17
    case _22 = 18
    case _23 = 19
    case _24 = 20
    case _25 = 21
    case _26 = 22
    case _27 = 23
    case _28 = 24
    case _29 = 25
    case _30 = 26
    case _31 = 27
    case _32 = 28
    case _33 = 29
    case _34 = 30
    case _35 = 31
    case _36 = 32
    case _37 = 33
    case _38 = 34
    case invalid = 0xFF
}
