/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.191.0Release
// Tag = production/release/21.191.0-0-g3eba15c
/////////////////////////////////////////////////////////////////////////////////////////////

public enum FitBaseUnit: UInt16, CaseIterable, Sendable {
    case other = 0
    case kilogram = 1
    case pound = 2
    case invalid = 0xFFFF
}
