/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

public enum FontGradingScale: UInt8, CaseIterable, Sendable {
    case _1 = 0
    case _2 = 1
    case _3 = 2
    case _4 = 3
    case _4Plus = 4
    case _5 = 5
    case _5Plus = 6
    case _6a = 7
    case _6aPlus = 8
    case _6b = 9
    case _6bPlus = 10
    case _6c = 11
    case _6cPlus = 12
    case _7a = 13
    case _7aPlus = 14
    case _7b = 15
    case _7bPlus = 16
    case _7c = 17
    case _7cPlus = 18
    case _8a = 19
    case _8aPlus = 20
    case _8b = 21
    case _8bPlus = 22
    case _8c = 23
    case _8cPlus = 24
    case _9a = 25
    case invalid = 0xFF
}
