/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

public enum FrenchGradingScale: UInt8, CaseIterable, Sendable {
    case _1 = 0
    case _2 = 1
    case _3 = 2
    case _4a = 3
    case _4b = 4
    case _4c = 5
    case _5a = 6
    case _5b = 7
    case _5c = 8
    case _6a = 9
    case _6aPlus = 10
    case _6b = 11
    case _6bPlus = 12
    case _6c = 13
    case _6cPlus = 14
    case _7a = 15
    case _7aPlus = 16
    case _7b = 17
    case _7bPlus = 18
    case _7c = 19
    case _7cPlus = 20
    case _8a = 21
    case _8aPlus = 22
    case _8b = 23
    case _8bPlus = 24
    case _8c = 25
    case _8cPlus = 26
    case _9a = 27
    case _9aPlus = 28
    case _9b = 29
    case invalid = 0xFF
}
