/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.193.0Release
// Tag = production/release/21.193.0-0-g249913a
/////////////////////////////////////////////////////////////////////////////////////////////

public enum IndoorBikeExerciseName: UInt16, CaseIterable, Sendable {
    case airBike = 0
    case assaultBike = 1
    case stationaryBike = 3
    case invalid = 0xFFFF
}
