/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.193.0Release
// Tag = production/release/21.193.0-0-g249913a
/////////////////////////////////////////////////////////////////////////////////////////////

public typealias LeftRightBalance = UInt8

public struct LeftRightBalanceValues: Sendable {
    public static let mask: LeftRightBalance = 0x7F
    public static let right: LeftRightBalance = 0x80
    public static let invalid = 0xFF
}
