/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.188.0Release
// Tag = production/release/21.188.0-0-g55050f8
/////////////////////////////////////////////////////////////////////////////////////////////

public enum LeftRightBalance: UInt8, CaseIterable, Sendable {
    case mask = 0x7F
    case right = 0x80
    case invalid = 0xFF
}
