/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.200.0Release
// Tag = production/release/21.200.0-0-g28b5705d
/////////////////////////////////////////////////////////////////////////////////////////////

public enum NapPeriodFeedback: UInt8, CaseIterable, Sendable {
    case none = 0
    case multipleNapsDuringDay = 1
    case jetlagIdealTimingIdealDuration = 2
    case jetlagIdealTimingLongDuration = 3
    case jetlagLateTimingIdealDuration = 4
    case jetlagLateTimingLongDuration = 5
    case idealTimingIdealDurationLowNeed = 6
    case idealTimingIdealDurationHighNeed = 7
    case idealTimingLongDurationLowNeed = 8
    case idealTimingLongDurationHighNeed = 9
    case lateTimingIdealDurationLowNeed = 10
    case lateTimingIdealDurationHighNeed = 11
    case lateTimingLongDurationLowNeed = 12
    case lateTimingLongDurationHighNeed = 13
    case idealDurationLowNeed = 14
    case idealDurationHighNeed = 15
    case longDurationLowNeed = 16
    case longDurationHighNeed = 17
    case invalid = 0xFF
}
