/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.218.0Release
// Tag = production/release/21.218.0-0-g96fee6d7
/////////////////////////////////////////////////////////////////////////////////////////////

public enum SaxonGradingScale: UInt8, CaseIterable, Sendable {
    case i = 0
    case iI = 1
    case iII = 2
    case iV = 3
    case v = 4
    case vI = 5
    case vIIA = 6
    case vIIB = 7
    case vIIC = 8
    case vIIIA = 9
    case vIIIB = 10
    case vIIIC = 11
    case iXA = 12
    case iXB = 13
    case iXC = 14
    case xA = 15
    case xB = 16
    case xC = 17
    case xIA = 18
    case xIB = 19
    case xIC = 20
    case xIIA = 21
    case xIIB = 22
    case xIIC = 23
    case invalid = 0xFF
}
