/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.218.0Release
// Tag = production/release/21.218.0-0-g96fee6d7
/////////////////////////////////////////////////////////////////////////////////////////////

public enum UiaaGradingScale: UInt8, CaseIterable, Sendable {
    case i = 0
    case iI = 1
    case iII = 2
    case iVMinus = 3
    case iV = 4
    case iVPlus = 5
    case vMinus = 6
    case v = 7
    case vPlus = 8
    case vIMinus = 9
    case vI = 10
    case vIPlus = 11
    case vIIMinus = 12
    case vII = 13
    case vIIPlus = 14
    case vIIIMinus = 15
    case vIII = 16
    case vIIIPlus = 17
    case iXMinus = 18
    case iX = 19
    case iXPlus = 20
    case xMinus = 21
    case x = 22
    case xPlus = 23
    case xIMinus = 24
    case xI = 25
    case xIPlus = 26
    case xIIMinus = 27
    case invalid = 0xFF
}
