/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

public enum VerminGradingScale: UInt8, CaseIterable, Sendable {
    case vb = 0
    case v0 = 1
    case v1 = 2
    case v2 = 3
    case v3 = 4
    case v4 = 5
    case v5 = 6
    case v6 = 7
    case v7 = 8
    case v8 = 9
    case v9 = 10
    case v10 = 11
    case v11 = 12
    case v12 = 13
    case v13 = 14
    case v14 = 15
    case v15 = 16
    case v16 = 17
    case v17 = 18
    case invalid = 0xFF
}
