/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

public enum YdsGradingScale: UInt8, CaseIterable, Sendable {
    case _51 = 0
    case _52 = 1
    case _53 = 2
    case _54 = 3
    case _55 = 4
    case _56 = 5
    case _57 = 6
    case _58 = 7
    case _59 = 8
    case _510 = 9
    case _510a = 10
    case _510b = 11
    case _510c = 12
    case _510d = 13
    case _511 = 14
    case _511a = 15
    case _511b = 16
    case _511c = 17
    case _511d = 18
    case _512 = 19
    case _512a = 20
    case _512b = 21
    case _512c = 22
    case _512d = 23
    case _513 = 24
    case _513a = 25
    case _513b = 26
    case _513c = 27
    case _513d = 28
    case _514 = 29
    case _514a = 30
    case _514b = 31
    case _514c = 32
    case _514d = 33
    case _515 = 34
    case _515a = 35
    case _515b = 36
    case _515c = 37
    case _515d = 38
    case _51Minus = 39
    case _51Plus = 40
    case _52Minus = 41
    case _52Plus = 42
    case _53Minus = 43
    case _53Plus = 44
    case _54Minus = 45
    case _54Plus = 46
    case _55Minus = 47
    case _55Plus = 48
    case _56Minus = 49
    case _56Plus = 50
    case _57Minus = 51
    case _57Plus = 52
    case _58Minus = 53
    case _58Plus = 54
    case _59Minus = 55
    case _59Plus = 56
    case _510Minus = 57
    case _510Plus = 58
    case _511Minus = 59
    case _511Plus = 60
    case _512Minus = 61
    case _512Plus = 62
    case _513Minus = 63
    case _513Plus = 64
    case _514Minus = 65
    case _514Plus = 66
    case _515Minus = 67
    case _515Plus = 68
    case invalid = 0xFF
}
