/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.201.0Release
// Tag = production/release/21.201.0-0-g39a0a60c
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

public class BitStream {
    private let bitsPerPosition: Int

    private var values: [any Numeric]
    internal private(set) var bytes: [UInt8] = []

    public private(set) var position: Int = 0
    public private(set) var bitsAvailable: Int = 0

    private var currentByte: UInt8 = 0
    private var currentBit: Int = 0
    
    enum BitStreamError: Error {
        case noBitsAvailable
        case tooManyBitsRequested
        case invalidBaseTypeSize
    }
    
    public convenience init(value: any Numeric, baseTypeSize: Int) throws {
        try self.init(values: [value], baseTypeSize: baseTypeSize)
    }
    
    public init(values: [any Numeric], baseTypeSize: Int) throws {
        guard baseTypeSize > 0 else {
            throw BitStreamError.invalidBaseTypeSize
        }
        self.bitsPerPosition = baseTypeSize * 8
        self.values = values
        self.bitsAvailable = bitsPerPosition * values.count
    }
         
    func readBit() throws -> UInt8 {
        if (!hasBitsAvailable()) {
            throw BitStreamError.noBitsAvailable
        }

        if bytes.isEmpty {
            try initializeBytes()
        }
        
        if (currentBit >= 8) {
            try nextByte()
        }
        
        let bit = currentByte & 0x01
        currentByte = currentByte >> 1
        currentBit += 1
        bitsAvailable -= 1
        
        return bit
    }
    
    func readBits(_ nBitsToRead: Int) throws -> Int64 {
        if (nBitsToRead > 64) {
            throw BitStreamError.tooManyBitsRequested
        }

        // Fast path: if reading exactly one value's worth of bits and bytes haven't been initialized yet
        if nBitsToRead == bitsPerPosition && bytes.isEmpty {
            if bitsAvailable <= 0 {
                throw BitStreamError.noBitsAvailable
            }
            let index = values.count - (bitsAvailable / bitsPerPosition)
            let value = Int64(bitPattern: UInt64(fitValue: values[index]))
            bitsAvailable -= bitsPerPosition
            return value
        }
        
        var value: Int64 = 0
        
        for i in 0..<nBitsToRead {
            value |= Int64(try readBit()) << i
        }
        
        return value
    }
    
    public func reset() throws {
        bytes = []
        position = 0
        bitsAvailable = bitsPerPosition * values.count
        currentByte = 0
        currentBit = 0
    }

    private func initializeBytes() throws {
        for value in values {
            bytes += value.bytes
        }
        let consumed = values.count - (bitsAvailable / bitsPerPosition)
        position = consumed * (bitsPerPosition / 8)
        try nextByte()
    }
    
    public func nextByte() throws {
        if (position >= bytes.count) {
            throw BitStreamError.noBitsAvailable
        }
        
        currentByte = bytes[position]
        position += 1

        currentBit = 0
    }
    
    public func hasBitsAvailable() -> Bool {
        return bitsAvailable > 0
    }
}
