/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.212.0Release
// Tag = production/release/21.212.0-0-g0676a0e3
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

public class BitStream {
    private let bitsPerPosition: Int
    private let baseType: BaseType

    private var values: [any Numeric]
    internal private(set) var bytes: [UInt8] = []

    public private(set) var position: Int = 0
    public private(set) var bitsAvailable: Int = 0

    private var currentByte: UInt8 = 0
    private var currentBit: Int = 0
    
    enum BitStreamError: Error {
        case noBitsAvailable
        case tooManyBitsRequested
    }
    
    public convenience init(value: any Numeric, baseType: BaseType) throws {
        try self.init(values: [value], baseType: baseType)
    }
    
    public init(values: [any Numeric], baseType: BaseType) throws {
        self.baseType = baseType
        self.bitsPerPosition = Int(baseType.size) * 8
        self.values = values
        self.bitsAvailable = bitsPerPosition * values.count
    }
         
    func readBit() throws -> UInt8 {
        if (!hasBitsAvailable()) {
            throw BitStreamError.noBitsAvailable
        }

        if bytes.isEmpty {
            try initializeBytes()
        }
        
        if (currentBit >= 8) {
            try nextByte()
        }
        
        let bit = currentByte & 0x01
        currentByte = currentByte >> 1
        currentBit += 1
        bitsAvailable -= 1
        
        return bit
    }
    
    func readBits(_ nBitsToRead: Int, signed: Bool) throws -> Int64 {
        if (nBitsToRead > 64) {
            throw BitStreamError.tooManyBitsRequested
        }

        // Fast path: if reading exactly one value's worth of bits and bytes haven't been initialized yet
        if nBitsToRead == bitsPerPosition && bytes.isEmpty {
            if bitsAvailable <= 0 {
                throw BitStreamError.noBitsAvailable
            }
            let index = values.count - (bitsAvailable / bitsPerPosition)
            var value = Int64(bitPattern: BitStream.rawBits(of: values[index]))
            bitsAvailable -= bitsPerPosition
            if signed { value = BitStream.signExtend(value, bits: nBitsToRead) }
            return value
        }
        
        var value: Int64 = 0
        
        for i in 0..<nBitsToRead {
            value |= Int64(try readBit()) << i
        }
        if signed {
            value = BitStream.signExtend(value, bits: nBitsToRead)
        }
        return value
    }
    
    public func reset() throws {
        bytes = []
        position = 0
        bitsAvailable = bitsPerPosition * values.count
        currentByte = 0
        currentBit = 0
    }

    private func initializeBytes() throws {
        for value in values {
            bytes += value.bytes
        }
        let consumed = values.count - (bitsAvailable / bitsPerPosition)
        position = consumed * (bitsPerPosition / 8)
        try nextByte()
    }
    
    public func nextByte() throws {
        if (position >= bytes.count) {
            throw BitStreamError.noBitsAvailable
        }
        
        currentByte = bytes[position]
        position += 1

        currentBit = 0
    }
    
    public func hasBitsAvailable() -> Bool {
        return bitsAvailable > 0
    }

    private static func signExtend(_ value: Int64, bits: Int) -> Int64 {
        guard bits > 0 && bits < 64 else { return value }
        let shift = 64 - bits
        return (value << shift) >> shift
    }

    private static func rawBits(of value: any Numeric) -> UInt64 {
        switch value {
        case let v as UInt8:  return UInt64(v)
        case let v as UInt16: return UInt64(v)
        case let v as UInt32: return UInt64(v)
        case let v as UInt64: return v
        case let v as Int8:   return UInt64(UInt8(bitPattern: v))
        case let v as Int16:  return UInt64(UInt16(bitPattern: v))
        case let v as Int32:  return UInt64(UInt32(bitPattern: v))
        case let v as Int64:  return UInt64(bitPattern: v)
        case let v as Float32: return UInt64(v.bitPattern)
        case let v as Float64: return v.bitPattern
        default: fatalError("Unsupported numeric type in BitStream")
        }
    }
}