/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.202.0Release
// Tag = production/release/21.202.0-0-g9a57aebc
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

public class CrcCalculator {
    private static let crcTable: [UInt16] = [
        0x0000, 0xCC01, 0xD801, 0x1400, 0xF001, 0x3C00, 0x2800, 0xE401,
        0xA001, 0x6C00, 0x7800, 0xB401, 0x5000, 0x9C01, 0x8801, 0x4400
    ]
    
    public private(set) var crc: UInt16 = 0;
    
    private static func updateCRC(_ value: UInt8, crc: UInt16) -> UInt16 {
        let table = crcTable
        var crc = crc

        // Compute checksum of lower four bits of byte
        var tmp = table[Int(crc) & 0xF]
        crc = (crc >> 4) & 0x0FFF
        crc = crc ^ tmp ^ table[Int(value) & 0xF]

        // Compute checksum of upper four bits of byte
        tmp = table[Int(crc) & 0xF]
        crc = (crc >> 4) & 0x0FFF
        crc = crc ^ tmp ^ table[(Int(value) >> 4) & 0xF]

        return crc
    }

    public func updateCRC(_ value: UInt8) -> UInt16 {
        self.crc = CrcCalculator.updateCRC(value, crc: self.crc)
        return self.crc
    }
    
    static func calculateCRC(data: Data) -> UInt16 {
        var crc: UInt16 = 0
        for byte in data {
            crc = updateCRC(byte, crc: crc)
        }
        return crc
    }
}
