/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.195.0Release
// Tag = production/release/21.195.0-0-g569e7e5
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

public class InputStream {
    private let data: Data
    private let bytes: ContiguousArray<UInt8>
    public private(set) var position: Int = 0

    enum InputStreamError: Error {
        case positionIndexOutOfRange
        case numberOfBytesProvidedIsLongerThanNumberOfBytesRemaining
    }

    public init(data: Data) {
        self.data = data
        self.bytes = ContiguousArray(data)
        self.position = 0;
    }

    public func readNumeric<T>(endianness: Endianness = Endianness.little) throws -> T {
        let size = MemoryLayout<T>.size

        if (size > bytes.count - position) {
            throw InputStreamError.numberOfBytesProvidedIsLongerThanNumberOfBytesRemaining
        }

        var value: T = bytes.withUnsafeBytes { buffer in
            buffer.loadUnaligned(fromByteOffset: position, as: T.self)
        }

        if (endianness == Endianness.big && size > 1) {
            withUnsafeMutableBytes(of: &value) { ptr in
                for i in 0..<(size / 2) {
                    let tmp = ptr[i]
                    ptr[i] = ptr[size - 1 - i]
                    ptr[size - 1 - i] = tmp
                }
            }
        }

        position += size

        return value
    }

    public func readString(size:UInt8) throws -> String {
        if (size > bytes.count - position) {
            throw InputStreamError.numberOfBytesProvidedIsLongerThanNumberOfBytesRemaining
        }

        let string = bytes.withUnsafeBytes { buffer in
            let slice = UnsafeRawBufferPointer(rebasing: buffer[position..<position+Int(size)])
            return String(decoding: slice, as: UTF8.self)
        }

        position += Int(size)

        return string
    }

    public func reset() throws -> Void {
        try seek(position: 0);
    }

    public func seek(position: Int) throws -> Void {
        if (position > bytes.count - 1) {
            throw InputStreamError.positionIndexOutOfRange
        }
        self.position = position;
    }

    public func peekByte() -> UInt8 {
        return bytes[position]
    }

    var hasBytesAvailable: Bool {
        return position < bytes.count
    }

    // MARK: Array Like Methods
    public var count: Int {
        return bytes.count
    }

    public subscript(bounds: Range<Data.Index>) -> Data {
        return self.data[bounds]
    }

    public subscript(bounds: ClosedRange<Data.Index>) -> Data {
        return self.data[bounds]
    }

    public subscript(index: Int) -> UInt8 {
        return self.bytes[index]
    }
}
