/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.201.0Release
// Tag = production/release/21.201.0-0-g39a0a60c
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

public class InputStream {
    private let data: Data
    public private(set) var position: Int = 0
    
    enum InputStreamError: Error {
        case positionIndexOutOfRange
        case numberOfBytesProvidedIsLongerThanNumberOfBytesRemaining
        case skipCountMustBePositive
    }
    
    public init(data: Data) {
        self.data = data
        self.position = 0;
    }
    
    public func readNumeric<T>(endianness: Endianness = Endianness.little) throws -> T {
        let size = MemoryLayout<T>.size
        
        if (size > data.count - position) {
            throw InputStreamError.numberOfBytesProvidedIsLongerThanNumberOfBytesRemaining
        }
        
        let value: T = data.withUnsafeBytes { bytes in
            if endianness == .big {
                return withUnsafeTemporaryAllocation(byteCount: size, alignment: MemoryLayout<T>.alignment) { buf in
                    for i in 0..<size {
                        buf[i] = bytes[position + size - 1 - i]
                    }
                    return buf.load(as: T.self)
                }
            } else {
                return bytes.loadUnaligned(fromByteOffset: position, as: T.self)
            }
        }
        
        position += size
        
        return value
    }
    
    public func readString(size:UInt8) throws -> String {
        if (size > data.count - position) {
            throw InputStreamError.numberOfBytesProvidedIsLongerThanNumberOfBytesRemaining
        }
        
        let string = String(decoding: data[position..<position+Int(size)], as: UTF8.self)
        
        position += Int(size)
        
        return string
    }
    
    public func reset() throws -> Void {
        try seek(position: 0);
    }
    
    public func seek(position: Int) throws -> Void {
        if (position > data.count - 1) {
            throw InputStreamError.positionIndexOutOfRange
        }
        self.position = position;
    }

    public func skip(_ count: Int) throws -> Void {
        if (count < 0) {
            throw InputStreamError.skipCountMustBePositive
        }

        let destination = self.position + count

        if (destination > data.count - 1) {
            throw InputStreamError.positionIndexOutOfRange
        }

        self.position = destination
    }
    
    public func peekByte() -> UInt8 {
        return data[position]
    }
        
    var hasBytesAvailable: Bool {
        return position < data.count
    }
    
    // MARK: Array Like Methods
    public var count: Int {
        return data.count
    }
    
    public subscript(bounds: Range<Data.Index>) -> Data {
        return self.data[bounds]
    }

    public subscript(bounds: ClosedRange<Data.Index>) -> Data {
        return self.data[bounds]
    }
    
    public subscript(index: Int) -> UInt8 {
        return self.data[index]
    }
}
